### ISSUE TITLE
[after some crash] Slax with persistence hangs in the middle of boot -- CPU gets 100% loaded

### ISSUE THREAD

**Issue by sskras** [Tomas-M/linux-live#10]
or **Dynfilefs needs fsck**.

---
## What happened?

After some crash on my box, **Slax 7** stalls.  By rebooting it several times and finally by unchecking "Persistent Changes" option I got it to boot fine.

In cleanly booted Slax I have checked and found the file of interest, it's ~350 MiB in size:

**# ls -Alh /mnt/live/memory/data/slax/changes/changes.dat**
-rwxr-xr-x 1 root root 349M Apr  9 04:14 /mnt/live/memory/data/slax/changes/changes.dat           

I tried to mount it:

**# /mnt/live/bin/mount.dynfilefs /mnt/live/memory/data/slax/changes/changes.dat 350 /media/**

Seems fine for now:

**# ls -Al /media**
total 0
-r--r--r-- 1 root root 367001599 Jan  1  1970 loop.fs

(from the 2nd terminal)

**# iostat 1**
avg-cpu:  **%user**   %nice **%system** %iowait  %steal   %idle
           **0.50**    0.00    **0.50**    0.00    0.00   99.00

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.00         0.00         0.00          0          0
sdf               0.00         0.00         0.00          0          0

avg-cpu:  **%user**   %nice **%system** %iowait  %steal   %idle
           **1.50**    0.00    **0.50**    0.00    0.00   98.00

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.00         0.00         0.00          0          0
sdf               0.00         0.00         0.00          0          0

But a soon as I try to access the file, my box gets loaded:

**# file /media/loop.fs**

(doesn't return; switching to the 2nd terminal)

**# iostat 1**
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          **11.56**    0.00    **1.01**    0.00    0.00   87.44

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.00         0.00         0.00          0          0
sdf               0.00         0.00         0.00          0          0

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          **26.50**    0.00   **22.00**   28.50    0.00   23.00

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.00         0.00         0.00          0          0
sdf               0.00         0.00         0.00          0          0

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          **27.27**    0.00   **27.78**    0.00    0.00   44.95

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.00         0.00         0.00          0          0
sdf               0.00         0.00         0.00          0          0

(repeating with same values forever)

And the culprit is:

**# ps -e -o pcpu,pmem,args --sort=pcpu | tail -n 5**
 0.7  1.1 kdeinit4: konsole [kdeinit]
 1.2  1.3 /usr/bin/X :0 vt7 -auth /var/run/xauth/A:0-ZKJqTa
 4.9 23.3 /usr/bin/firefox -P default
 5.6  1.8 /usr/lib/firefox-19.0.2/plugin-container /usr/lib/mozilla/plugins/libflashplayer.so -greomni /usr/lib/firefox-19.0.2/omni.ja 2402 plugin
**66.0**  0.0 /mnt/live/bin/**mount.dynfilefs** /mnt/live/memory/data/slax/changes/changes.dat 350 /media/

Cancelling my user-cmd isn't possible from console:

**# file /media/loop.fs**
^^C^^^C^_

So I need to kill it along with **mount.dynfilefs**.

---
## What I expect?

1, to be able to extract my data from the **changes.dat** .
1a, to be able to read the corrupt /media/**loop.fs** .

2, to have a tool to deal with that in future.
2a, we probably need **fsck.dynfilefs** .

**Comment by saulius2** [comment]
Ping. Will someone help me to extract my precious data in reliable way?

**Comment by Tomas-M** [comment]
closing old bugs, if your problem persists, try newest code from github and report back. Thank you and sorry for not helping with this.
