### ISSUE TITLE
Mouse pointer error with 20 04 focal fossa

### ISSUE THREAD

**Issue by blue-devil-93** [Tomas-M/linux-live#102]
Hi,
Did a debootatrap chroot with ubuntu focal fossa and  created a livecd. Then added a loopback.cfg file to the iso boot from grub2 grml script. Iso stored on ssd.

Everything works as expected except the mouse once i attach one with changable dpi. Don't know if its related to the live script.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
