### ISSUE TITLE
mounting aufs on /memory/union failed: invalid argument

### ISSUE THREAD

**Issue by txsastre** [Tomas-M/linux-live#104]
hi.
I've created an very tiny Debian 10 ISO without GUI.
once generated the ISO it starts (I can see the yellow background) it starts and then it says

mounting aufs on /memory/union failed: invalid argument

any clue ? 

thanks.

![Selecció_459](https://user-images.githubusercontent.com/10468371/77423056-d99f2e80-6dce-11ea-870c-23c5f7671630.jpg)

**Comment by Tomas-M** [comment]
Most likely you are missing aufs kernel module

**Comment by txsastre** [comment]
thank you !  I also found this solution here in the issues.
now it works fine !

**Comment by txsastre** [comment]
hello again.
I created a new ISO with debian 10 but this time is a 32 bits.
I'm having again the same problem, and I have installed
- aufs-dkms
- geniosoimage
- squashfs-tools

**Comment by Tomas-M** [comment]
Please make sure you are using current master branch of linux-live.
You may need to disable apparmor in your Debian 10, like this:
https://github.com/Tomas-M/linux-live/blob/master/Slax/debian10/rootcopy/usr/lib/systemd/system/apparmor.service
