### ISSUE TITLE
file too big

### ISSUE THREAD

**Issue by millerthegorilla** [Tomas-M/linux-live#105]
is there any way of configuring linux-live script so that it will accept files over the current maximum size?
I want to have variety installed, and the build script is complaining and stopping because an image file is too large.

**Comment by Tomas-M** [comment]
image file is too large? you mean iso image? How much large it is?

**Comment by millerthegorilla** [comment]
not the iso image, just an image file.  message is write failed because file too large.  However, the file is a jpg that is the wallpaper clock of Variety, a desktop wallpaper manager, that I want to include.  The clock is updated every minute, so perhaps the change is detected, and this is causing problems.
If I turn it off, though, it won't be turned on in the finished image.
I guess I could turn it off and then edit the config file once I have unpacked the image.

**Comment by Tomas-M** [comment]
I have no clue what you are talking about, sorry.
