### ISSUE TITLE
Ubuntu 20.04 - No Partition Tables on ISO

### ISSUE THREAD

**Issue by KaiLikesLinux** [Tomas-M/linux-live#106]
I am a developer for a distribution of Ubuntu and I have seen people mention this issue on our first release: ![alt](https://pbs.twimg.com/media/EVDsHoUUUAkEffJ?format=png&name=900x900)

I was wondering if there was any possible fixes or anything I could do to get the ISO working so the people interested in my product can use it! Thank you in advance.

           - Kai

**Comment by Tomas-M** [comment]
ISO does not have a partition table.

**Comment by KaiLikesLinux** [comment]
I am not sure what you mean by "ISO does not have a partition table.",  I need this fixed, my community needs this to work and this is the issue that everyone has been reporting as the context. I am equally sure that you're right with the fact that "ISO's don't use partition tables" but at the same time I need an understanding of why this pops up and how to fix the issue.

I even ran the script a 2nd time today and used my install of Balena Etcher and got the same, may I know some fix or resource? @Tomas-M

**Comment by Tomas-M** [comment]
Well, it looks to me that the screenshot you posted shows some third party application, balenaEtcher, which shows the error message. Well, that is not my software and I am not responsible for it and I do not know why it prints such error message. I have no idea what is the function of that software. I could just guess that it takes the ISO image and tries to put it to an USB stick? That is plainly wrong.

ISO image is to be burned to a CD or DVD disc.

If you wish to put the LiveCD on an USB stick, you have to unpack the contents of the ISO file (as like if it was a zip archive, for example) to your USB disk, and then setup boot record on your USB disk (see /linux/boot/bootinst.bat).

Alternatively, you may try to find some ways to convert the ISO image to a bootdisk image, using "isohybrid" command perhaps?

**Comment by KaiLikesLinux** [comment]
@Tomas-M, BalanaEtcher is software that does USB formating with ISO files, and it is normal for it to work with ISO files with USB (By formating the drive). It is a non-issue of it being a USB drive. The issue is in the ISO itself as I get screenshots of broken VMs as well as Etcher errors and other software giving errors or not-booting. It is irrelevant if it is USB or not, something I need to understand about the ISO making end. Thank you.
