### ISSUE TITLE
chroot

### ISSUE THREAD

**Issue by alt-magick** [Tomas-M/linux-live#107]
I have the same problem as someone else, but I couldn't get his solution to work. It looks like this:

switch root from initramfs to ramfs
Live Kit init http://www.linux-live.org/
Setting dynamic RAM compression using ZRAM if available
Probing for hardware
Looking for linux data in /linux ...
Found on dev/sr0
Setting up unions using AUFS
mount: mounting aufs on /memory/union failed: No such device
Adding bundles to union
01-core.sb
mount: mounting aufs on /memory/union failed: Invalid argument
/init: line 52: can't create /memory/union/etc/fstab: nonexistent directory
/init: line 52: can't create /memory/union/etc/fstab: nonexistent directory
/init: line 52: can't create /memory/union/etc/fstab: nonexistent directory
/init: line 52: can't create /memory/union/etc/fstab: nonexistent directory
/init: line 52: can't create /memory/union/etc/fstab: nonexistent directory
Live Kit done, starting linux
ln: sbin/fsck.aufs: No such file or directory
Fatal error occured - Can't find executable chroot command

The other guys said to install aufs-dkms, but I get the same error when booting off the live cd. My DVD has only one directory "/linux". I guess it isn't setup right.  Please help find a solution, ty.

**Comment by powercrypt** [comment]
I tried runing isolinux.bin.update as well and got more errors...

powercrypt@kali:/a/tools$ sudo ./isolinux.bin.update 
[sudo] password for powercrypt: 

--------------------------------------
Add directory to isolinux search paths
(for example /slax/boot): /slax/boot
Reading package lists... Done
E: You must put some 'deb-src' URIs in your sources.list

**Comment by sdolenc** [comment]
I'm not sure for kali linux, but the fix for "deb-src" in ubuntu (and presumably other debian-variants) is described here

https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list

hope that helps!

**Comment by sdolenc** [comment]
I just read the part where you said you already un-commented the deb-src entries. Woops. Sorry you already tried most of the the advice from that askubuntu post. I don't know the correct fix required offhand

**Comment by powercrypt** [comment]
I'm trying again with Debian. I'll let you know how it goes.

**Comment by powercrypt** [comment]
It works on Debian! But I can't seem to connect to my wifi.  Ideas on that one?

**Comment by LothaireCliquennois** [comment]
> 
> 
> It works on Debian! But I can't seem to connect to my wifi. Ideas on that one?

You are probably missing a firmware, you should try building an ISO with a non-free installation ISO.

https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
