### ISSUE TITLE
Can't install the live environment (Debian, but applies to others, probably)

### ISSUE THREAD

**Issue by LothaireCliquennois** [Tomas-M/linux-live#108]
Hey there, 
I just wanted to have some further information.
As you're the dev of the Slax live environment, and the creator of this tool, did you ever have any luck installing one of your live environments ?
Basically I tried adding Calamares, Ubiquity, and Debian Installer to my ISOs, and all of my tries were in vain.
If you know anyone that got good experiences with using your tool + an installer, just let me know please !

**Comment by xXTeraXx** [comment]
I have gotten Calamares to work successfully after a long time trying.   Calamares is hard to install though, requiring you to put in a bunch of config files. I did it by installing the Calamares deb package then adding in the setting.conf and other config files to /usr/calamares 

I have not installed yet but will report back to and tell you what happened with the install

btw:You need to make sure that the user settings are the default for all users or else when calamares goes and makes the new user it will just have the default for that desktop environment

**Comment by LothaireCliquennois** [comment]
Oh okay, so there are files to add inside of the /usr/calamares ?
Could you send me the files please ?

**Comment by xXTeraXx** [comment]
Okay here they are, these are the 2 that are needed for calamares to launch https://github.com/calamares/calamares/blob/master/src/branding/default/branding.desc

https://github.com/calamares/calamares/blob/master/settings.conf

Just put the files in /usr/calamares.

HUGE TIP:run this command sudo apt-get purge --remove libboost-all-dev && sudo apt-get purge --remove libboost*

Then install this dependency: http://ftp.br.debian.org/debian/pool/main/b/boost1.67/libboost-python1.67.0_1.67.0-13+deb10u1_amd64.deb

Then use this calamares deb file 
http://ftp.br.debian.org/debian/pool/main/c/calamares/calamares_3.2.4-3_amd64.deb


This is what worked for me

**Comment by LothaireCliquennois** [comment]
Well, I tried for a while to play with what you sent me, and was unsuccesful.
Maybe there's problems with LMDE, as I was able to do it properly on Debian 10 vanilla

**Comment by Ponycius** [comment]
Hi. I'm trying to make a live distro of Debian 11 with KDE Plasma and I tried adding Calamares as an installer.
The process goes well until the installation itself. It tells me that the "unsquash" setting is invalid, the source file system "/run/live/medium/live/filesystem.squashfs" does not exists. 
Where is this filesystem.squashfs located on linux-live? And how can I configure this setting?

Thanks for the patience

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
