### ISSUE TITLE
Slax

### ISSUE THREAD

**Issue by powercrypt** [Tomas-M/linux-live#109]
I installed Slax & got Linux Live Kit to work with it, but I can't find much documentation on Slax.  Could someone tell me how to keep program icons on the desktop like any other OS?

**Comment by LordBoltar** [comment]
as far as I know Slax does not have the ability to put icons on desktop, they appear when you click the menu button

**Comment by Tomas-M** [comment]
You can start xlunch in desktop mode to put icons on desktop
