### ISSUE TITLE
fstab

### ISSUE THREAD

**Issue by suedi** [Tomas-M/linux-live#11]
With my understanding there is no way to add entries to fstab
since it is re-written every time the system boots.

Would it be possible to add some way of facillitating this
for intstance adding something similar to rc.local that is if a file /etc/fstab.local exist
add the lines to fstab at startup

at the end of fstab_create add
[ -e "$1/etc/fstab.local" ] && cat "$1/etc/fstab.local" >> $FSTAB 

Why do you feel the need to explicitly write fstab on each boot?

best regards

suedi

**Comment by Tomas-M** [comment]
Make a startup script which adds your desired lines to the freshly created fstab
