### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by alt-magick** [Tomas-M/linux-live#110]
I successfully installed Linux Live Kit on Linux Mint! It worked after running ./isolinux.bin.update in the Tools directory. At first I got this error:

E: You must put some 'source' URIs in your sources.list

And then I ran "software-properties-gtk" in the terminal.  All I had to do was click "add sources" and run isolinux.bin.update again.  Once that completed everything else worked fine.  So here is my question....

Is there a way to permanently install Linux Live Kit, or do I always need the CD?

**Comment by sdolenc** [comment]
I think the scenario you're describing could be accomplished with MX Linux. It comes with a tool to export your installed os and I believe that export can be installed to other machines (not just a live image). I haven't tried it myself.

**Comment by sdolenc** [comment]
> Is there a way to permanently install Linux Live Kit, or do I always need the CD?

You could run the ISO as the boot "device" for a virtual machine on a host. You don't get any data persistence between reboots, but it's one way of not needing a physical CD

**Comment by KaiLikesLinux** [comment]
I have had success with this error by just recompiling isolinux.update.bin 2 or 3 times before formatting the ISO

**Comment by LothaireCliquennois** [comment]
I think that the thing this dude wants, just like me, is to have a way to install the live system, with a Calamares, Deb-Installer, or Ubiquity.

Someone was very grateful to try to help me however I couldn't do it on LMDE 4.
There seems to be a grey place in the Linux community when it comes to installers.
It's very sad, as it'll be much easier to use Linux Live Kit

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
