### ISSUE TITLE
Slow Live Image creation

### ISSUE THREAD

**Issue by Kevin87114** [Tomas-M/linux-live#111]
I am trying to create a USB bootable image of my current system so the test software on it can be used without having Linux installed on the customer's PC.

I have followed the directions like Steps 1-4 state with associated docs(README); edited config, logged in as root and ran build. I am not running /tmp as tmpfs
<pre><font color="#8AE234"><b>User@User</b></font>:<font color="#729FCF"><b>~</b></font>$ df -T /tmp
Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/sda1      ext4 302374328 27832264 259159280  10% /
</pre>
I keep getting to the point:
Failed to read file /proc/kallsyms, creating empty file
[=================/                                 ] 45000223/314414685  35%
where it gets to 20 odd percent it slows down and runs for days and when 99% is reached it never stops, where leaving it running for a week after does nothing. This 35% seen here is after three days of running.

I have tried this three times and get the same thing
I even have 'proc' defined as ignore;
`MKMOD="proc sys tmp etc media lib lib64 root srv usr"`

running 18.04LTS

Any help or advice would be greatly appreciated.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
