### ISSUE TITLE
"Boot error"

### ISSUE THREAD

**Issue by andrija-tosic** [Tomas-M/linux-live#112]
When I try booting from a USB stick, I just get "Boot error" and then it says to press any key to restart. Running the bootinst.bat was successful apparently.

**Comment by LothaireCliquennois** [comment]
Hello, this software is roumanified.
I have similar issues with booting Ubuntu live CDs done with Linux Live Kit.

**Comment by KaiLikesLinux** [comment]
I have had very similar issues when using Linux Live Kit for anything Ubuntu-based, knowing my previous experiences with Tom, he will most likely close the issue saying something like "you can't put ISO's on USB"

May I ask which tool/setup did you use? Also which particular distribution

**Comment by Tomas-M** [comment]
In order to boot a LiveCD from USB, you need to
1) setup your USB drive so it uses MBR partition scheme (gpt wont work)
2) create at least one partition on your USB
3) format that partition with FAT32 filesystem for example
4) mount your USB drive and copy LiveCD data to it
5) run bootinst.bat from your usb drive (it is in /linux/boot/ directory) to setup boot record.

**Comment by LothaireCliquennois** [comment]
>     5. run bootinst.bat from your usb drive (it is in /linux/boot/ directory) to setup boot record.

How are you supposed to run a .bat on Linux :D
We're not talking Windows man ;)

Also, what you described is exactly what Rufus or Etcher does when set up correctly ^^

**Comment by Tomas-M** [comment]
If you actually see inside the bootinst.bat file, you will notice that it is specially written that it works on BOTH windows and linux. It is a trick to make it executable on some linuxes, which mount the USB drive with showexec parameter by default - resulting in incorrect attributes, so only exe, com and bat file extensions are executable.

**Comment by LothaireCliquennois** [comment]
> 
> 
> If you actually see inside the bootinst.bat file, you will notice that it is specially written that it works on BOTH windows and linux. It is a trick to make it executable on some linuxes, which mount the USB drive with showexec parameter by default - resulting in incorrect attributes, so only exe, com and bat file extensions are executable.

Oh, that's really interesting, thanks for the info ;)

**Comment by wangzhankun** [comment]
> In order to boot a LiveCD from USB, you need to
> 
> 1. setup your USB drive so it uses MBR partition scheme (gpt wont work)
> 2. create at least one partition on your USB
> 3. format that partition with FAT32 filesystem for example
> 4. mount your USB drive and copy LiveCD data to it
> 5. run bootinst.bat from your usb drive (it is in /linux/boot/ directory) to setup boot record.

Which filesystem is supported? I cannot use fat32 because my file is bigger than 4G and fat32 is not supported.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
