### ISSUE TITLE
Boot via UEFI = Black Screen *Solved*

### ISSUE THREAD

**Issue by Just-Ch33s3** [Tomas-M/linux-live#113]
Hi! First of all, thanks for this great tool!
As ive read through the new uefi support comments it seems that there are still issues regarding a black (or blank) screen (?) when i try to UEFI Boot with my Live Stick, on my Notebook i have the ability to just boot in Legacy Mode, which works fine but UEFI on several systems doesn't.
Is there someone who can help me out ? Should the newest Repo files already work with UEFI or is this still WIP ?
Cheers, have a good day and thanks for your help!

**Comment by Just-Ch33s3** [comment]
just as an addition, this is my current /EFI Folder which got generated after running the bootinst.sh on ubuntu (without errors)
![grafik](https://user-images.githubusercontent.com/49145093/82092809-3a295880-96fa-11ea-9424-d460fc716b24.png)

**Comment by Just-Ch33s3** [comment]
after several hours of trial & error rebooting / formatting pendrives back and fourth i forgot to put it back to -: FAT32 :- , the only accepted filetype for UEFI, got both menu32 and vesamenu working !

**Comment by Tomas-M** [comment]
Thank you for info!
