### ISSUE TITLE
Arch Linux Error cannot stat /vmlinuz No surch file or directory

### ISSUE THREAD

**Issue by dinooz** [Tomas-M/linux-live#114]
cp: cannot stat '/vmlinuz': No such file or directory

Git clone https://github.com/Tomas-M/linux-live.git

cd /tmp/linux-live

sudo ./build

**Comment by Just-Ch33s3** [comment]
hi, first of all be aware that /tmp files will be gone after reboot.
regarding the /vmlinuz problem, check your local drive for the "vmlinuz" file and get its path.
then edit the config.ini inside the live kit

**Comment by maytanthegeek** [comment]
So on `arch`, the path should be something like `/boot/vmlinuz-linux`

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.

**Comment by connected201** [comment]
hi, i have same error! ubuntu 20.04

**Comment by connected201** [comment]
```
root@ubuntu:/home/ubuntu/linux-live-2.5# ls
bootfiles  bootinfo.txt  build  config  DOC  initramfs  livekitlib  README  Slax  tools
root@ubuntu:/home/ubuntu/linux-live-2.5# ./build
Changing current directory to /home/ubuntu/linux-live-2.5
Building initramfs image...
cp: cannot stat '/vmlinuz': No such file or directory


root@ubuntu:/tmp# cd linux-data-45927/ 
root@ubuntu:/tmp/linux-data-45927# ls 
linux 
root@ubuntu:/tmp/linux-data-45927# cd linux 
root@ubuntu:/tmp/linux-data-45927/linux# ls 
boot  changes  modules 
root@ubuntu:/tmp/linux-data-45927/linux# 

```

**Comment by swapnilchincholkar** [comment]
@connected201 Ubuntu has `vmlinuz` under `/boot` directory. 
So as per @Just-Ch33s3, 
- simply change the `config` file of extracted linux-live i.e `/tmp/linux-live-2.6/config` 
- and look for `/vmlinuz` update it to `/boot/vmlinuz`, save it  and proceed.
