### ISSUE TITLE
Making bootable ISO for virtualbox

### ISSUE THREAD

**Issue by ivernus** [Tomas-M/linux-live#118]
I've managed to get the bootable USB to work @Tomas-M , I've tried converting it back to an ISO (for use with Virtualbox) but to no avail, I've tried with dd and imgburn. Booting from the USB with plop works. 

 Do you have any instructions on how to do this? I will add tot he project docs if you have details somewhere.

**Comment by mjhorvath** [comment]
Same issue with VMware. The ISOs cause the "Failed to load ldlinux.c32" error.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
