### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by ghost** [Tomas-M/linux-live#120]
Is there a way to add persistence to the to the ISO similar to Slax

**Comment by Tomas-M** [comment]
Try creating directory /linux/changes

**Comment by LordBoltar** [comment]
ok thanks will do

**Comment by Naik-NLZ** [comment]
Hey there! I found /changes to be populated after I tweaked the system.
Would it be possible to add an encryption layer to persistence or 01-core.sb?

**Comment by wanpixiaozi** [comment]
My U disk has directory /linux/changes, but still can't use persistence function

**Comment by computermaster0101** [comment]
* If you plan to boot your Live Kit from USB device, you may wish to add
  the following boot parameter to the end of APPEND section in syslinux.cfg:
     perch
  This parameter activates persistent changes
  
  
  Hey everyone, if you are still having issues, please confirm the above was done. I'll help as I can.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
