### ISSUE TITLE
encryption for 01-core.sb or /changes

### ISSUE THREAD

**Issue by Naik-NLZ** [Tomas-M/linux-live#123]
Hey, is there a way to encrypt the main 01-Core.sb, or the persistent storage?

**Comment by gittig** [comment]
I forked and completely reconstrcted linux_live. It is now farely modular. Pleae hack it yourself to fit your taste. 
https://github.com/gittig/sys_convert_to_live_kit

new features:
      * ships with scripts to generate and load **luks encrypted squashfs root image**
      * luks cryptsetup is integrated in the initramfs
dropped features: 
      * persistent storage
      * gracefully shutdown
      * binary blobs has been dropped, you need to provide 3 binary files yourself.
new / lack of features:
      * the boot process is now manual instead of fully automatic. You need to load the squashfs root image in the initramfs shell environment.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
