### ISSUE TITLE
Install Live in Hard Disk

### ISSUE THREAD

**Issue by kleytonls** [Tomas-M/linux-live#125]
Hi Tomas-M,
Its possible to install this live on hard disk?

**Comment by amanullahtanweer** [comment]
Can any one help me as well on this, is there any way to install the iso file into Hard Disk

**Comment by oifii** [comment]
Hey guys, I got the same question. My linux-live works great, thanks to Thomas-M, but I would like to install it on hard disk. I build my custom version of kubuntu 20.04.2 desktop, but it was installed on a Virtualbox VM disk when did the linux-live build procedure. I thought I would be getting a live USB install I could not only boot from but also try/modify with option of installing to hard disk. Any help on this most welcome. Steph.

**Comment by computermaster0101** [comment]
Hey everyone,

I dont know if you figured this out or not yet. Please use the zip. Format disk with new partition table as MBR, unzip the zip to the root drive and follow instructions in readme.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
