### ISSUE TITLE
Can't create ISO.

### ISSUE THREAD

**Issue by AToska21** [Tomas-M/linux-live#126]
When I try to use /tmp/gen_figlinux_iso.sh to create the iso, I get the following error:
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.

I don't know how to use the argument -allow-limited-size. Can anyone help me?

Regards,
A Linux Creator

**Comment by LordBoltar** [comment]
Is you ISO larger then 4GBs ?

generally when I create an ISO in the tmp directory I run sudo bash ./gen_name of your ISO_iso.sh

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
