### ISSUE TITLE
File ./ubuntu2010/01-core.sb is larger than 4GiB-1.

### ISSUE THREAD

**Issue by Marietto2008** [Tomas-M/linux-live#127]
Finished. Find your result in /media/ziomario/Elements1/Backups/ubuntu2010-data-61180
To build ISO, run: /tmp/gen_ubuntu2010_iso.sh
To build ZIP, run: /tmp/gen_ubuntu2010_zip.sh

root@ziomario-z390aoruspro:/home/ziomario/Scrivania/Items-SDA/remasterSYS/Tomas-M-linux-live-e0709f2# /tmp/gen_ubuntu2010_iso.sh

I: -input-charset not specified, using utf-8 (detected in locale settings)
genisoimage 1.1.11 (Linux)
Scanning .
Scanning ./ubuntu2010
File ./ubuntu2010/01-core.sb is larger than 4GiB-1.
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.

01-core.sb = 178,1 GB

what should I do ?

NB : I've understood bymyself that I should edit the file gen_ubuntu2010_iso.sh should be modified adding the parameter -allow-limited-size,like this :

/usr/bin/mkisofs -allow-limited-size -o /tmp/ubuntu2010-x86_64.iso -v -J -R -D -A ubuntu2010 -V ubuntu2010 -no-emul-boot -boot-info-table -boot-load-size 4 -b ubuntu2010/boot/isolinux.bin -c ubuntu2010/boot/isolinux.boot .

**Comment by NodokaHanamura** [comment]
I've yet to get my distro to work, but I'd recommend doing as you mentioned above, and if you need to make it bootable from USB, insert your USB, copy over the files from your ISO to the USB (Don't clone it, mount the ISO and USB, move the files over) and then run the shell script to change the file. I advise formatting in ext2.

**Comment by FaffeF** [comment]
178.1 GB, is that intended? Are you going to live boot a usb full of movies?

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
