### ISSUE TITLE
poor documentation.

### ISSUE THREAD

**Issue by Marietto2008** [Tomas-M/linux-live#128]
The documentation is very poor. ok for the advanced users,not ok for the newbies. improve it. To write something like this :

Download Linux Live Kit from GitHub and put it in /tmp. Read files in ./DOC/ to learn how it works (this step is optional). Edit .config file if you need to modify some variables. 

it was valid when internet is born,a lot of time ago,because the first users were advanced already and they didn't need at all to read "read the doc" ; but now,after 30 years or more,it makes no sense anymore. Now there are a lot of people who are looking for a good documentation because they want to learn and they want to do it fast. Don't include it means to live in the past,on the first time when internet is born.

**Comment by 666threesixes666** [comment]
i agree, im trying to make a built usb that stands on its own and runs into a compressed live cd image.  funtoo undead usb.  uncompressed / on usb works fine.  where do i mount it to?  ive been looking at the scripts and documentation for over 2 hours.  =D  i have the build modified to be passwordless and autologin to the "funtoo" root user through slim.  i have squashfs tools mkisofs and most of the dependencies, just i don't have a clue as to where to load the directory containing the bootable linux system.
