### ISSUE TITLE
How to save persistent changes storage

### ISSUE THREAD

**Issue by wanpixiaozi** [Tomas-M/linux-live#130]
I want to save some work on usb live, but find after reboot, all info reset, who can give me examples or tips on how to save persistence changes on usb live. Thanks a lot.

**Comment by wanpixiaozi** [comment]
@Tomas-M Do you have any idea?

**Comment by Tomas-M** [comment]
You need supported filesystem on your usb, and you need boot parametr to activate changes, which I do not remember :)

**Comment by wanpixiaozi** [comment]
Thanks @Tomas-M , i found the para, perch, no issue now.
