### ISSUE TITLE
Ubuntu 18 hungup with legacy mode

### ISSUE THREAD

**Issue by wanpixiaozi** [Tomas-M/linux-live#131]
![ubuntu-hang](https://user-images.githubusercontent.com/39391886/99863650-352df000-2bda-11eb-9690-eab439843067.png)
My Ubuntu18.04 hung up as above, only if i chose **legacy** mode on bios, if i choose **UEFI** it can successfully boot. 
Does anyone has such issue or can give me any tip? Thanks. @Tomas-M @glensc @mintsoft

**Comment by mintsoft** [comment]
Absolutely no idea from me I'm afraid

**Comment by wanpixiaozi** [comment]
vga=769 is the root cause, i remove it from cmdline, and it works

**Comment by wanpixiaozi** [comment]
no issue now
