### ISSUE TITLE
USB boot files - Could not locate linux data

### ISSUE THREAD

**Issue by joelgraff** [Tomas-M/linux-live#133]
I've been trying to make linux-live work for an EFI system with marginal success.  I have managed to get Slax to boot on the same system, so I know it's possible.

To this point, I've managed to successfully build an image of a vanilla install of ubuntu 18.04 and copied out the ZIP contents to the USB in the prescribed manner.  running bootinst.sh also works without issue.  The system recognizes the UEFI boot option and attempts to boot, but when it switches over to linux-live, it eventually terminates with the "Could not locate linux data" error.

I'm certain my directory structure is correct (see below).  The USB stick is 8 GB, and is a single MSDOS partition (not GPT).

Any tips on what might be wrong?

File Structure:

 .  
 ├── EFI
 │   └── Boot
 │       ├── bootx64.efi
 │       ├── ldlinux.e64
 │       ├── libcom32.c32
 │       ├── libutil.c32
 │       ├── menu.c32
 │       ├── syslinux.cfg
 │       ├── syslinux.efi
 │       └── vesamenu.c32
 ├── linux
 │   ├── 01-core.sb
 │   ├── boot
 │   │   ├── bootinst.bat
 │   │   ├── bootinst.sh
 │   │   ├── bootlogo.png
 │   │   ├── EFI
 │   │   ├── extlinux.x32
 │   │   ├── extlinux.x64
 │   │   ├── initrfs.img
 │   │   ├── isolinux.bin
 │   │   ├── ldlinux.c32
 │   │   ├── ldlinux.sys
 │   │   ├── libcom32.c32
 │   │   ├── libutil.c32
 │   │   ├── mbr.bin
 │   │   ├── pxelinux.0
 │   │   ├── syslinux.cfg
 │   │   ├── syslinux.com
 │   │   ├── syslinux.exe
 │   │   ├── vesamenu.c32
 │   │   └── vmlinuz
 │   ├── changes
 │   └── modules
 └── readme.txt

 7 directories, 28 files

**Comment by novaburst-dev** [comment]
I have tried the same , but using an openSUSE base OS , and legacy boot method , it fails even with the root= kernel parameter.

**Comment by olsztyn1** [comment]
I have exactly the same issue on debian based distro.
Build process works fine and the USB stick starts booting but then it fails to find 'linux data', although /linux directory is on the stick. No changes to cfg was made, so all default.
Is this linux-live kit supported at all, as I see these issues lingering for months and no response appears to be posted?
This would be a pity as this live build process seemed so good...
Thanks for any help...

**Comment by Tomas-M** [comment]
The error means it couldn't find the compressed data (.sb modules).
When you get the error, you are given a bash prompt. Try to investigate - try to list visible partitions (cat /proc/partitions), try to mount the USB disk to some directory, try to read a file from the usb disk. If this fails, try to find out why that fails, see dmesg for example.

**Comment by blownfuse** [comment]
This is a similar issue to #98.  I'm having the same problem with a Fedora 35 distro.  It seems it might be a problem with the drives we're using?

**Comment by computermaster0101** [comment]
Hey Tomas,

I did a lsmod | grep usb 

Is this what you need? 
usb_storage            77824  1 uas

If you need a full output of lsmod please let me know, i can produce.

**Comment by computermaster0101** [comment]
Figured it out. UAS driver is USB Attached SCSII. This is the driver Linux and Windows refers to when the USB device is attached. I referred to https://github.com/Tomas-M/linux-live/issues/83 to identify the driver. 

used 
usb-devices
to identify the driver is uas

used modinfo uas to identify driver location. 

once the driver location was identified i was able to update initramfs_create to include 
copy_including_deps /$LMK/kernel/drivers/usb/storage/uas.*

**Comment by Tomas-M** [comment]
To be honest, I do not know how to fix that mouse, really.
You can try adding more USB drivers to see what helps.
You can even try to add all USB drivers like this:

copy_including_deps /$LMK/kernel/drivers/usb

However if you want me to include proper fix to linux-live kit, I will need to know only the few particular drivers which are really needed. I cannot include all linux drivers for all devices in default initramfs, it's more than 200 MB, it is impossible to add all.
