### ISSUE TITLE
Ubuntu 20.04 Live ISO Does Not Boot: "Fatal error occurred - Could not locate linux data"

### ISSUE THREAD

**Issue by milan-patartics** [Tomas-M/linux-live#136]
First of all I want to say how fascinating this tool is. I want to create custom live ISO-s from existing installs many years ago, but I was not able to manage to get it done the way I prefer. Your tool looks like to be exactly what I need to have to setup my fine-tuned live distros.

But after spending literally two and a half days on it, I still can not make it work.

Does not matter what I do, what I try, I always end up at the same error:
![Screenshot](https://user-images.githubusercontent.com/52017436/107882440-a1727400-6ee9-11eb-94bb-bffbd116adf0.png)

I am trying to create my customized Ubuntu 20.04 Focal Fossa.

For testing purposes, I just installed a fresh Ubuntu, made some updates and cleanup and set some regional settings.
I installed the dependencies of Linux Live Kit without any problem.

Then I did the followings:

1. Downloaded the linux-live-kit
2. Extracted the zip file to /tmp
3. Changed the config file (set LIVEKITNAME to "ubuntu"; set VMLINUZ to "/boot/vmlinuz")
4. Ran the isolinux.bin.update script in the tools directory.
5. Copied the generated files from the tools directory to the bootfiles directory.
6. Ran the build script
7. Created the ISO file with the gen_ubuntu_iso.sh script

I tried the third step with customized name like "ubuntu", but I also tried it with the default "linux" one.

I entered the proper input for the isolinux.bin.update script: "/ubuntu/boot" for LIVEKITNAME="ubuntu" OR "/linux/boot" for LIVEKITNAME="linux")

During the execution of the isolinux.bin.update script I saw the following warnings:
```
ld: cannot find /usr/lib/crt0-efi-ia32.o: No such file or directory
ld: skipping incompatible /usr/lib/libgnuefi.a when searching for -lgnuefi
ld: cannot find -lgnuefi
ld: skipping incompatible /usr/lib/libefi.a when searching for -lefi
ld: cannot find -lefi
make[3]: [/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1/efi/Makefile:76: syslinux.so] Error 1 (ignored)
/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1/efi32/efi/wrapper syslinux.so syslinux.efi
fopen: No such file or directory
make[3]: [/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1/efi/Makefile:97: syslinux.efi] Error 1 (ignored)
make[3]: Leaving directory '/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1/efi32/efi'
make[2]: Leaving directory '/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1/efi32'
make[1]: Leaving directory '/tmp/syslinux/syslinux-6.04~git20190206.bf6db5b4+dfsg1'
```

During the sixth step I noticed two warnings:
```
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_default
```

Otherwise all the scripts finished successfully and seemed to run well.
I got my nice ISO at the end, and I tried to boot from it, but always throws the same error as mentioned above.

Kernel version: 5.8.0-43-generic

I would really appreciate if you could guide me to fix this issue, or if you could let me know what did I wrong or what did I miss. I am clueless at this point.

I was wanting to make bootable live ISO-s from existing Ubuntu installs many years ago, I would be very happy if finally I would be able to make it.

Thanks a lot!

**Comment by Brutus11111** [comment]
I can confirm this bug.

Linux Live Versions tested:
2.4
2.3

Linux distro's tested:
Debian 8 
Debian 10

I did not change the config file at all. Steps taken:

```
cd /tmp
wget https://github.com/Tomas-M/linux-live/tarball/master
mv master master.tar
tar xf master.tar
cd Tomas-M-linux-live-e0709f2
apt install squashfuse squashfs-tools genisoimage
./build
cd /tmp
./gen_linux_iso.sh
```

**Comment by Tomas-M** [comment]
First of all, lets eliminate any possible issue with isolinux.bin.update  - skip this entirely and leave your LIVEKITNAME set to "linux".
If the error you get is what can be seen on the screenshot in this case, it means it wasn't able to load kernel driver (.ko module) for your storage device.

Assuming you get the screenshot above, it means the following:
- your live CD properly boots into isolinux bootloader
- the bootloader properly loads kernel and initramfs image from the boot media (assuming CD ROM)
- linux-live-kit procedure starts, and tries to find the live data. This step fails.

What happens during this phase:
- it tries to modprobe all available kernel modules which were added to initramfs during creation
- it then tries to mount all hard drives and cd roms and other possible storage devices
- then it tries to find some file with .sb extension in directory /linux on your storage devices (function find_data() in file livekitlib in sources)

So, if this is not successfull, it means that either your storage device couldn't be found (eg. missing driver) or it couldn't be mounted (unsupported filesystem, unlikely) or it does not contain any *.sb file (unlikely). Most likely the first will be the issue, if your kernel does not have built-in driver for your cdrom, then it cannot see it. Livekit tries to add additional kernel modules (drivers) to initramfs but their name is hardcoded and maybe your driver is missing. See initramfs_create script in sources, there are bunch of lines starting with copy_including_deps, you may need to add copying of the particular drivers you need for your storage device.

When you get the error message during boot saying it couldn't find live data, try to use 'lsmod' to see what modules are loaded. Try to mount your storage device (eg. cdrom) to some temporary directory.

**Comment by Brutus11111** [comment]
![xBZ3CXr](https://user-images.githubusercontent.com/42470867/112158763-c349cf80-8be8-11eb-8f24-018fa0878736.jpg)

I made this one without isolinux.bin.update

[lsmod of live iso (Debian 8)](https://termbin.com/uxc7)

[lsmod after installing (Debian 8)](https://termbin.com/19dvx)

[lscpu](https://termbin.com/acuz)

[lshw](https://termbin.com/5o3r)

[lspci](https://termbin.com/4e2e)

I wanted to create a live ISO that I could plug into any computer, no matter what brand or type, and boot it, just like a normal live ISO.

**Comment by milan-patartics** [comment]
> So, if this is not successfull, it means that either your storage device couldn't be found (eg. missing driver) or it couldn't be mounted (unsupported filesystem, unlikely) or it does not contain any *.sb file (unlikely). Most likely the first will be the issue, if your kernel does not have built-in driver for your cdrom, then it cannot see it. Livekit tries to add additional kernel modules (drivers) to initramfs but their name is hardcoded and maybe your driver is missing. See initramfs_create script in sources, there are bunch of lines starting with copy_including_deps, you may need to add copying of the particular drivers you need for your storage device. @Tomas-M

I tested the generated ISO with burned DVD and also with Virtualbox VM-s.
The kernel version: 5.8.0-43-generic; I think both (physically and Virtualbox) drivers are supported by the kernel by default.

I think the issue is happening because of something else. Isn't the kernel version above 5.0 is the problem (#129)?
I mean the lack of support. Or am I wrong?

**Comment by Brutus11111** [comment]
The kernel I'm currently testing with is version 3.16.0-6-amd64

On the website it says "Make sure that aufs and squashfs kernel modules are supported by your kernel. Debian Jessie has both included automatically. You may need to install aufs-dkms package on newer versions of Debian."

I googled it and Jessie seems to be the same as Debian 8 so I thought I'd use that before trying to get a new version working.

Currently waiting for another attempt with Debian 10.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by milan-patartics** [comment]
> You may need to install aufs-dkms package on newer versions of Debian.

I have aufs-dkms installed on the OS I used to test linux-live.

**Comment by Brutus11111** [comment]
I installed aufs-dkm OS. So far, I'm now able to boot it as a virtual machine. I'm not able to boot it on a physical machine.

![SBVO6sG](https://user-images.githubusercontent.com/42470867/112297668-791f2780-8c96-11eb-9e72-ebda433541de.jpg)

**Comment by milan-patartics** [comment]
> I installed aufs-dkms on Debian 10. So far, I'm now able to boot it as a virtual machine. I'm not able to boot it on a physical machine.

Good news, unfortunately not working with Ubuntu.
What could be the difference? Is it the kernel version?

**Comment by Brutus11111** [comment]
> > I installed aufs-dkms on Debian 10. So far, I'm now able to boot it as a virtual machine. I'm not able to boot it on a physical machine.
> 
> Good news, unfortunately not working with Ubuntu.
> What could be the difference? Is it the kernel version?

Well, good news, it still won't boot. It's now only working in a VM, but that's not all that helpful.

**Comment by milan-patartics** [comment]
> Well, good news, it still won't boot. It's now only working in a VM, but that's not all that helpful.

I agree. Personally one of my main goals is to use it in VM-s, so I will give a try with Debian 10 too.
But undoubtedly is would be useful to run it on physical machines. I also want to do so.

**Comment by Brutus11111** [comment]
For me it's to have an ISO file to boot any and all computer with custom software already installed, ready to go

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by shipstonesec** [comment]
Newest Debian has also dropped support for aufs-dkms and installing it now may require use of an unsigned kernel enhancement.  (That breaks several things so is a no-go for me.)   The developer of aufs has said they were giving up the fight (https://marc.info/?l=linux-kernel&m=123938442923108) .

Tomas, with much respect to you for this beloved project, do you plan to migrate to a supported mount?  Or would you prefer we fork such efforts?  Thank you!

**Comment by Tomas-M** [comment]
Regarding missing aufs support in your distro, there are some unofficial patches for linux live kit where some person tried to use in-kernel overlay filesystem instead of aufs and he claimed it works, but i'm not sure where such patches are and if they actually worked as advertised. I didn't like it so I didn't test it.

**Comment by Brutus11111** [comment]
https://drive.google.com/file/d/1AM2vNkQht_K2BDwUIOdHY60IdSKMNBkO/view?usp=sharing

That's Debian 8 in ISO format that I build, that's recommended on the website. I can't get it running. This should have the aufs support. Where is it going wrong and how do I fix it so it works on any hardware.

**Comment by Tomas-M** [comment]
Your ISO boots just fine. Screenshot attached.
![VirtualBox_Slax test 64_26_03_2021_21_46_05](https://user-images.githubusercontent.com/2259370/112690850-c230d080-8e7c-11eb-8345-9480cc755937.png)

If it cannot load on your computer then it does not have drivers for your storage device from which you are booting. What is that device?

**Comment by Brutus11111** [comment]
It boots fine in a virtual machine

It's physical hardware that's the issue. I tested it on multiple computers, with new NVME M.2 drives, mSATA SSD, SATA SSD and conventional HDD. None of them boot. 

Example:

https://www.nexcom.com/Products/industrial-computing-solutions/industrial-fanless-computer/core-i-performance/fanless-pc-fanless-computer-nise-3600e

3rd gen intel computer with a QM77 chipset.

**Comment by Brutus11111** [comment]
Any idea?

I created an iso with the kernel from the live ISO that Debian provides themselves, that doesn't work either.

**Comment by Brutus11111** [comment]
Anything?

**Comment by Tomas-M** [comment]
Unfortunately I cannot help with this. You will need to find which kernel module you need to include, and then include it in your initramfs (modify create_initramfs script)

**Comment by milan-patartics** [comment]
@Thomas-M May I ask why did you close this? Brutus11111 kinda hijacked this thread, because he has different problems with a different OS and different kernel version.

But my initial issue is still valid. It does not work with Ubuntu 20.04. Probably because of the kernel version (but it is still unclear to me).

I would really appreciate if you could guide me how to make linux-live work with OS - like Ubuntu 20 - that has newer kernel.

**Comment by Tomas-M** [comment]
I didn't realize there are multiple people answering to this thread.
Basically, if your error is that it could not locate the live data, it means it tried to mount your boot device and find *.sb files on it, this failed. You are given a command prompt, so please try to investigate. lsmod will list your loaded modules, cat /proc/partitions will list your available devices, try to find out if your device is missing or what is the problem.

Newer kernel should not be an issue here, I believe.
Please let me know, what is your boot device (how is it connected, etc), and what devices you see in /proc/partitions

**Comment by davesbc** [comment]
Hi, im having almost identical problem. I made a live usb without probs, did not change default names, ran bootinst.sh with no errors but the usb shows cannot find linux data on boot.

Lsmod shows long list of loaded modules and /proc/partitions show the installed harddisks but not the usb it is booting from. However the usb must be accessible since the ugly boot image is loaded and the modules are loaded? Please help, thank you.
