### ISSUE TITLE
How to add kernel/boot  parameters?

### ISSUE THREAD

**Issue by Stewori** [Tomas-M/linux-live#137]
To workaround some issue on a targeted machine of my live usb stick I would like to setup some boot parameters.
E.g. what you would normally do with an installed linux:

```
sudo sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="pci=acpi acpi_irq_nobalance acpi=force lapic"/g' /etc/default/grub
sudo update-grub
```

How can I add such parameters for the live USB stick? I assume I would have to edit some startup script of the linux-live kit. Can someone point me to the right place? Thanks in advance!

**Comment by Stewori** [comment]
It appears such parameters might fit into this line: https://github.com/Tomas-M/linux-live/blob/master/bootfiles/syslinux.cfg#L12
Am I correct?

**Comment by Tomas-M** [comment]
Yes that is the correct place
