### ISSUE TITLE
microSD not bootable

### ISSUE THREAD

**Issue by nbinford1138** [Tomas-M/linux-live#141]
Hello,

We are attempting to boot Slax 9.11 from a microSD card. I have copied the initial download files and have tried both bootinst.bat and bootinst.sh for MBR. This appears fine.

It does appear to load kernel and start init, but gets stuck at "looking for Slax data in /slax..." and eventually fails to the command line. I can take this same microSD card and insert it to a microsd-to-USB adapter and it will boot fine, but the difference of course is microSD is a mmcblk device and USB is sdx device. 

At the command line after failure I can #ls /dev and see that there is no mmcblk device in the list even though that is where I am booting this far from. At that time I can insert and remove a USB and #ls /dev will show the sda device appear and remove. 
Alternatively if I go to this same command line by booting to a USB but forcing a failure at the same time (from=/something will do this) I can see the sda device in /dev, but inserting and removing a microSD still does not show a mmcblk device. 

I had attempted to recompile the kernel thinking there were some missing kernel modules. but while the kernel loads I get many other errors since I am not sure how to load the unique init for Slax. 

Can you offer any further advice or clues for me to search for?

Thank you,
Nathan

**Comment by nbinford1138** [comment]
*update*
I have made some progress. Found that when fully booted the necessary mmcblk drivers are loaded and function. Found where the .ko files live. Then found in the initrfs.img that they do not exist in /lib/modules/(uname -r)/kernel/drivers/mmc . Specifically I was focused on the mmc_block.ko, sdhci.ko, and sdhci-pci.ko drivers. I extracted the initrfs.img on another system, copied the Card and Host folders into the above mentioned mmc folder, recompressed the initrfs.img file and tried again. Of course it did not solve the issue. 
Now when I get to the command line of initrfs.img I can insmod the above mentioned .ko drivers, then I was able to add the mmcblk devices to /dev with mknod - eg.
# mknod /dev/mmcblk1 b 179 0

Then I mount to /memory/data and run ./init. It finds what it is looking for and starts to boot by loading the .sb modules. It fails though with a message 
"couldn't find an alternative telinit implementation to spawn"
and drops me at another command line. However this command line appears to be a more fully functioning Debian/Slax just not the GUI my customer is looking for. 

I am still interested in automating the above process and would be interested to know what the error message indicates. My google search so far indicates it may have something to do with Docker and/or permissions. 

Also my apologies for my poor terminology!

Cheers,
Nathan

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
