### ISSUE TITLE
Replace boot text with splash screen

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#143]
Is there a way to replace the boot text output with a splash screen (ex: using plymouth)?

**Comment by Tomas-M** [comment]
Currently no way, sorry about that.

**Comment by bert003** [comment]
Thanks for your reply. No problem. However, is there a plan to implement it maybe in the near future? Having that option would enhance the linux-live kit making it the obvious choice to create a live distribution. Thanks for all your work.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
