### ISSUE TITLE
Hybrid ISO Query

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#145]
Can I create a Hybrid ISO? Currently there is the option to create an ISO and/or a ZIP file.

Using the script provided to install the ISO on a USB device works fine but I was just wondering whether a Hybrid ISO is possible so that even using `dd`, the ISO can be copied to a USB device.

Thanks

**Comment by Tomas-M** [comment]
It is currently not supported.
It is, in my opinion, bad idea to `dd` the is to USB device anyway :)
