### ISSUE TITLE
SATA - virtio-scsi Issue

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#146]
I tested the ISO in VirtualBox, created a SATA hard disk and installed the ISO on it.

When the SATA controller type is changed from **AHCI** to **virtio-scsi**, the booting process keeps display: **looking for ISONAME data in /ISONAME** and then it fails with the message: Something went wrong...

When I change it back to AHCI, everything works like a charm.

Can someone explain this issue please?

**Comment by bert003** [comment]
Can it be due to the fact that the system is designed to boot from CD, DVD or USB and does not cater for such disk controllers?

**Comment by Tomas-M** [comment]
Most likely it does not add the required drivers for "virtio-scsi" support, whatever it is (I never heard about it). If you find out what kernel modues are necessary to support it, feel free to let me know and I will consider adding it to the liveCD creation process. Thanks

**Comment by bert003** [comment]
Ok thanks. Will reply if I find the required kernel modules.
