### ISSUE TITLE
ISO UEFI Boot

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#147]
Cannot seem to boot my ISO using UEFI. Here is what I did using VirtualBox.

1. I enabled EFI and when I boot, I got a screen where I have to manually specify the location of the bootloader. I located the EFI file but when I type its name and press Enter, nothing happens. The VM remains as it is.

2. I moved the EFI directory in the root of the ISO and tried booting again. This time, the VM shows that it is trying to locate the EFI file but nothing happens.

I downloaded the Clonezilla ISO to investigate and it seems to use GRUB to successfully boot in UEFI enabled systems.

Can you help me please? UEFI booting is important nowadays I guess. Thanks in advance.

**Comment by Tomas-M** [comment]
I did not test UEFI support yet. There are some patches which were added by some users, I think it was for USB UEFI support, I'm not sure what is needed to add UEFI support for ISO booting.

I will start working on UEFI support as soon as there are sufficient amount of Patrons (see patreon.com/slax for milestones and goals)
