### ISSUE TITLE
Confused on the installing script

### ISSUE THREAD

**Issue by mobilegmYT** [Tomas-M/linux-live#148]
Hello! I'm just a little bit confused on the readme. What does it mean by installing when you run the bootinst.sh script? Does it let you choose which device to install to? Currently I want to be able to flash a ISO to a USB stick, and then be able to run a bash file and be able to choose a device (like a hard drive on the PC or the current USB stick) to install the OS to, and enable persistance.

**Comment by Tomas-M** [comment]
You cannot flash ISO to your USB stick, it won't work.
You need to unpack its contents to your USB stick, as like if the ISO was a ZIP archive for example. There are tools for that.
The bootinst script has one purpose: to make the USB stick bootable. You must run the bootinst script from your USB device, it sets up the device you are running it from. It automatically detects which device you are starting it from and it makes that device bootable (in simple terms that means, if modifies first few bytes of the partition)

**Comment by Tomas-M** [comment]
It should become persistent as soon as you create /linux/changes directory on your boot media

**Comment by mobilegmYT** [comment]
> It should become persistent as soon as you create /linux/changes directory on your boot media

How? I distribute my os with a iso, so which step do I add it in? When I generate the folder with Linux live before then making the iso?

**Comment by Tomas-M** [comment]
Well, the directory should be created automatically in the ISO
https://github.com/Tomas-M/linux-live/blob/master/build#L45

So if your user copies the contents of the ISO to an USB disk, it should be copied too

**Comment by mobilegmYT** [comment]
> Well, the directory should be created automatically in the ISO
> https://github.com/Tomas-M/linux-live/blob/master/build#L45
> 
> So if your user copies the contents of the ISO to an USB disk, it should be copied too

But is it possible to add the folder in before making the ISO and have it work? It's a long story but basically due to how it's installed the ISO is booted directly.

**Comment by mobilegmYT** [comment]
> Well, the directory should be created automatically in the ISO
> https://github.com/Tomas-M/linux-live/blob/master/build#L45
> 
> So if your user copies the contents of the ISO to an USB disk, it should be copied too

Hmm, well if it's already created when it's flashed then why doesn't my files save on reboot?

**Comment by mobilegmYT** [comment]
So I tried copying the contents of the zip to my USB and everything boots. The changes folder still exists, but none of my edited files persist on reboot still.

**Comment by Tomas-M** [comment]
Can you upload your ZIP somewhere? Eg. sharegorilla.com
So I could test it myself

**Comment by mobilegmYT** [comment]
I uploaded a ISO generated from the same files as the zip a while ago: https://transfer.sh/17FgSBX/linux-x86_64.iso

**Comment by mobilegmYT** [comment]
> Can you upload your ZIP somewhere? Eg. sharegorilla.com
> So I could test it myself

Hello! I did a little research and got persistence working on my debian based OS. I just needed to add `slax.flags=perch,automount` to the end of the line with all the arguments in `/linux/boot/syslinux.cfg` and `/EFI/Boot/syslinux.cfg`! You could add this to the readme.

**Comment by Tomas-M** [comment]
Ah, I forgot to mention this, I am sorry!
You should be fine with just adding "changes,automount" to the boot parameters, no need for slax.flags= prefix

**Comment by mobilegmYT** [comment]
Oo ok
