### ISSUE TITLE
debian10 slax script error

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#154]
When I use slax activate, I get the following error:

cd: /sys/fs/aufs/: No such file or directory

/sys/fs contains bpf, btrfs, cgroup, ext4, fuse and pstore.

How should the script be modified please?

**Comment by bert003** [comment]
Sorry my mistake ... kindly delete this issue since it is irrelevant

**Comment by Tomas-M** [comment]
If you do not have AUFS support in Debian10, then linux-live kit uses overlayfs instead of aufs, and it is not possible to 'activate' (add another branch on the fly)
