### ISSUE TITLE
Not possible to connect to WiFi after soft reboot

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#155]
I connect to my home wifi and save changes in a bundle. So far so good.

Then when I reboot (restart), no wifi access points are detected and I cannot connect through wireless.

To be able to reconnect again, I have to physically shutdown the machine, power on and boot in the live system again.

Why is this happening please? Is it a problem with the generated initrd?

**Comment by bert003** [comment]
UPDATE: This happens when I connect, create a bundle and restart.

When I remove the bundle and sort start afresh, no issues with the wireless card and I can connect normally.

I am using connman.

Is there maybe a directory that is being excluded in savechanges which is in fact needed for it to work once connected to a network?

**Comment by bert003** [comment]
And why is there this code in init?

`# modprobe all devices excluding network drivers
modprobe_everything -v /drivers/net/`

Why are the network drivers being excluded?

**Comment by bert003** [comment]
UPDATE 2: When I suspend (not shutdown) and press the laptop's power button again, I log in and the wifi access point are back again.

Why is that? Any help please?

**Comment by Tomas-M** [comment]
The part of init which loads kernel modules using modprobe_everything function excludes network drivers, because those are not needed ad that phase of init. They can be loaded later. Nevertheless, this part is only necessary to load kernel modules to initialize the live environment, and then your actual distribution is started, and your distro handles loading of all modules itself.

To answer your initial question, I don't really know why your wifi is unusable after soft reboot. Unfortunately I have no idea.

**Comment by bert003** [comment]
@Tomas-M thanks for your reply. I cannot explain it but when I removed the -v part and created the live distro, the system booted to bash and the data directory was not mounted causing the boot process to fail.

Can you kindly explain?

**Comment by Tomas-M** [comment]
If you only removed the "-v /drivers/net/" part, that means it modprobed all kernel modules, including those in /drivers/net. That means it loaded all drivers, including drivers for network devices. If this caused the distro to stop booting, then I really have no explanation why. I don't know.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
