### ISSUE TITLE
Include more modules and drivers in initrd

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#156]
How can I include more modules and drivers in initrd? The generated initrd size is quite small compared to other distros and I would like to have the same contents like, for example, the original debian one?

**Comment by Tomas-M** [comment]
What particular driver are you missing?
You can edit initramfs_create script, and add more lines like
copy_including_deps /$LMK/kernel/drivers/....

You can include particular modules or even whole directories with kernel modules.

**Comment by bert003** [comment]
Thanks for the explanation. I will include more drivers as you suggested then.
