### ISSUE TITLE
Live Image created with the Kit is unable to run chromium browser

### ISSUE THREAD

**Issue by husim-983** [Tomas-M/linux-live#160]
On my Source installation (xubuntu-20.04-2 based), I have two browsers. Firefox works on the Live-Image created by the kit as it should. With all my preferences etc. intact. Only, I can't run Chromium at all. My first doubtful candidate was snapd daemon. But, apparantly, it is very much there. I wonder, if someone else had this issue too. And, if there is a work-around for this. Sporadically, the image shows network problems too. It happens, when I use an Online-Program outside of the browser for a certain task and when I use the Mediaview application for loading the Media List. During this period, however the Firefox can load all Sites visited! So, my Network is not at fault. I used LAN for this test session.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
