### ISSUE TITLE
LZO compression instead of XZ: better performance?

### ISSUE THREAD

**Issue by ex0ticOne** [Tomas-M/linux-live#164]
I'm doing some tests with my custom live kit on a older notebook and I find this interesting. 

The default parameter for compression on `mksquashfs` is `-comp xz 1024k`. This generates the 01-core.sb bundle, crucial part of the live kit. 

When I was using my live kit on an older piece of hardware, XZ compression created an extremely sluggish experience. 

After this, I tried the LZO compression algorithm, and this improved the system responsiveness and performance in a very significant way. 

My conclusion is that older hardware will suffer with the XZ compression due to the high compression rate of this algorithm. 

The files and it's dependencies takes more time to be uncompressed when they are called by the user in the live system, increasing the workload on the CPU (that needs to uncompress the files and load them at the same time). 

If you are experiencing a bad performance in your live kit, try a lighter compression algorithm.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
