### ISSUE TITLE
Bundle naming issue.... maybe?

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#166]
I just noticed that if the bundles do not start with a number, some files from a previous bundle are not present when the bundles are mounted using overlayfs.

Once they are given a number ex: 02-bundle1 and 03-bundle2 etc, everything works fine.

@Tomas-M can you kindly explain please? Or am I doing something wrong?

**Comment by Tomas-M** [comment]
The only difference should be in mount order.
Does it mount the bundles if you use names without numbers? Boot your live system and see /run/initramfs/memory/bundles/

**Comment by bert003** [comment]
The files in /run/initramfs/memory/bundles are there but, for example, I had a bundle which included libsdl1.2debian... when I removed the name from the bundle name, the files were there but the `ldconfig` did not list the library as installed. In fact, issuing an `apt-get install` installs the package as if it was never installed. When I then rename the bundle starting with a number, the files are there as well and ldconfig lists the library as installed.

I cannot understand what's happening...

**Comment by Tomas-M** [comment]
Mount order is important for libraries.
When you install new libraries, cache file (in /etc/ld.so.cache) is updated.
If your bundles are loaded in different order, your cache probably does not reflect the libraries which were installed in another bundles.

Basically you need to ensure that bundles are mounted in the same order as you created them.

You should be able to fix the cache by running `ldconfig` command without arguments.

**Comment by bert003** [comment]
I see... however the bundle in question starts with an a and the next one starts with an o so it is mounted afterwards. Without numbers I get the ldconfig issue. With numbers, they are still mounted in the same order but ldconfig shows that the SDL library is installed!!!

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
