### ISSUE TITLE
Script to build the small sized 01-core

### ISSUE THREAD

**Issue by bert003** [Tomas-M/linux-live#169]
Is there a script to build a minimal custom 01-core?

The standard Debian installation is far larger than the whole Slax ISO? So running linux-live on a standard installation results in a large bundle.

Maybe I can be redirected to what to remove or how to debootstrap to produce a minimal Debian install?

Thanks in advance.

**Comment by Tomas-M** [comment]
If you want to base your system on Slax, you can simply remove all unneeded .sb modules from the /slax/ directory and rebuild your ISO

**Comment by bert003** [comment]
Ok thanks. However I was curious as to how you managed to build such a small core .sb module.
