### ISSUE TITLE
initramfs_create + exfat

### ISSUE THREAD

**Issue by seba1452021** [Tomas-M/linux-live#175]
hola soy inexperto en el tema de manejar github, perdon si creo inconvenientes.
me intereso todo esto y queria saber sobre como añadir compativilidad a todo esto con exfat.
tengo la idea de instalar ventoy en una usb, selecciono "configurar particion", con esto dejo un espacio al final de la memoria.
en ese ultimo espacio quiero ubicar un sistema personalizado con linux-live-kit, pero al arrancar tendria problemas por no poder ser reconocido sda1 osea, la particion que para mi seria "ventoy" y de sistema de archivos tendria exfat....
encontre cosas como http://forum.puppylinux.com/viewtopic.php?p=24832&i=3
--------------
dato curioso, manejo el traductor deepl, https://www.deepl.com/translator .

**Comment by Tomas-M** [comment]
I didn't have mail notifications in the past so I overlooked most of the issues unfortunately.
So now I am closing all issues. Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
