### ISSUE TITLE
VMware Workstation 16 - Could not locate linux data

### ISSUE THREAD

**Issue by DemaxDragonTix12** [Tomas-M/linux-live#182]
![image](https://user-images.githubusercontent.com/84226755/142651929-b94a8d9e-262a-43c7-905e-e4320ca79ab6.png)
So I wanna make a my own ubuntu distro and I tried booting to vmware workstation 16 and I get this error... I tried switching from SCSI to SATA, changed to VMware Workstation 12, didn't work

Any ideas?

**Comment by DemaxDragonTix12** [comment]
I did not also edit the iso image... the iso config is set to default

**Comment by mapagm** [comment]
I had the same issue. I created new virtual machine with SATA hard disk (instead of default SCSI) and preallocated space. Now it works for me.
![screenshot 1646311188](https://user-images.githubusercontent.com/28437752/156566529-2fa0ef51-7dd0-4a51-afef-fd9776ce94a3.png)

**Comment by computermaster0101** [comment]
I believe you are missing scsi drivers in your linux-live build.

**Comment by Tomas-M** [comment]
I didn't have mail notifications in the past so I overlooked most of the issues unfortunately.
So now I am closing all issues. Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
