### ISSUE TITLE
unable to boot past grub prompt

### ISSUE THREAD

**Issue by xcorvis** [Tomas-M/linux-live#183]
I recently created a new bootable ISO and I am unable to boot into linux. At the grub prompt selecting any boot option just returns to the grub prompt. There may be an error but it's too fast to read. My boot ISO is based on ubuntu 20.04, and I use a scripted process that worked previously.

The grub boot prompt shows the image is /linux/boot/vmlinuz-5.4.0-91-generic, but it looks like that file is not actually copied to the ISO. Editing the boot prompt to use /linux/boot/vmlinuz instead causes the ISO to boot normally.

This commit is the problem: https://github.com/Tomas-M/linux-live/pull/173

I believe it is editing the syslinux.cfg to include the kernel value, but then it's still copying the original vmlinuz file that doesn't include the kernel value. I have not tested it, but the bootinst.bat file edit doesn't account for the kernel version either, so it might also have issues.

I rebuilt with 2.4 instead of master, and my ISO worked normally.

I suggest reverting the PR, since I believe including the kernel version is unnecessary. The vmlinuz file is a symlink to the current kernel version, so it's not necessary to capture that information and make things more complex. If someone has a setup where they don't have the symlink or need to force a kernel version, they can edit the config file instead of the build script, which is a more flexible fix anyway.

**Comment by Tomas-M** [comment]
Hm, I now I understand it better.
I guess that the commit 173 can be preserved and one more change is needed, to copy the actual real file (vmlinuz-with-version) to the ISO.
There is this line
cp $VMLINUZ $BOOT/ || exit
I think it should be changed to 
cp $VMLINUZ $BOOT/$KER || exit

Is it feasible for you to test if this fixes your issue?

**Comment by xcorvis** [comment]
Sorry, I'm unable to easily test that. The code I have for building is a bit cumbersome and it would take longer than I want.

I don't see why the commit is necessary in the first place. You're copying the file that was symlinked, not the symlink. At least, unless your linux version uses a weird default config for cp. The `cp $VMLINUZ $BOOT` command could use a -L flag if that's the case. All the commit adds is an explicit version number on the file name, which IMO is completely unnecessary in a boot CD with only one bootable kernel.

Also, I believe it will cause problems if you're building a boot ISO with a different kernel than you're currently running from. It forces you to use the current build kernel. That's why the $KERNEL var exists in the config file, right?

If you do still want to include the kernel version I'd prefer a fix like this in the config file (after reverting the other commit):
```
VMLINUZ=/vmlinuz
```
to:
```
VMLINUZ=$(basename $(readlink -f /vmlinuz))
```

I think this would have the same effect, but be more flexible and user customizable. It could be the default or commented out in the file as an option. Someone who doesn't need the kernel version can just point it back at /vmlinuz or /boot/vmlinuz, or hard code a specific kernel version if you need to build while booted from a different kernel version. With the change in the build file you can't do something like that.

**Comment by Tomas-M** [comment]
I have to agree with you.
I've reverted the pull request. here d81a3f2cfe484abd87d84ac7448d382cfcc2d215
