### ISSUE TITLE
Could not locate rickos data

### ISSUE THREAD

**Issue by wooter6928196219911** [Tomas-M/linux-live#185]
![Screenshot_20211217_175404](https://user-images.githubusercontent.com/89206182/146580229-65daf9d7-7a7d-41ea-9805-b28f1f3373c2.png)

Please help, I will never gonna give my distro up, Never let my distro down, Never run around it and desert it.

**Comment by tree-t** [comment]
Hello @wooter6928196219911,
Can you share your config file?
And the contents of rickos/ ?

**Comment by Tomas-M** [comment]
I didn't have mail notifications in the past so I overlooked most of the issues unfortunately.
So now I am closing all issues. Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
