### ISSUE TITLE
Logs of build actions available?

### ISSUE THREAD

**Issue by blownfuse** [Tomas-M/linux-live#186]
I'm attempting to build a live USB image, capturing a Fedora 35 image I've created in VMware.  Plenty of vRAM for the machine, and one dual core vCPU.  tmpfs is mounted to /tmp with 10G of space.  I edited the config file to customize the LIVEKITNAME and point the VMLINUZ parameter to the proper /boot/<vmlinux kernel filename> as reflected by uname -r.  

The problem is when I run ./build it will get about 12% of the way through, and then quit and exit the CLI with no apparent error logs.

Anyone have any similar issues?  Are there logs of the build process anywhere that I can examine?  Thanks for any help you can provide!

**Comment by blownfuse** [comment]
You can see thing get kicked off correctly:
![image](https://user-images.githubusercontent.com/28966540/147861533-5fc72014-f170-4c4b-9e1b-477101105732.png)

**Comment by blownfuse** [comment]
Well, I upped to 2 dual core vCPU, and stopped the clamav services, and now I can get the build process to 34% or so before it just stops.

**Comment by blownfuse** [comment]
Ok, after removing a few more Fedora packages, I also added the "-info -progress" and then commented out "|| exit" on the mksquashfs line, and I'm able to get the build to complete successfully.   Seems somehow during some of the larger copy actions the process would just exit? Either way, this workaround works.

**Comment by Tomas-M** [comment]
I do not really understand why those two parameters could help at all, there must be a different issue I guess. Unfortunately I cannot help with this
