### ISSUE TITLE
Slax VNC Server on Headless System is not working.

### ISSUE THREAD

**Issue by Spamm00r** [Tomas-M/linux-live#188]
Hi,

I'm running latest Slax and wanted to access it via vnc. But unfortunately VNC does not work on headless systems when no monitor is connected.

This is a known problem and the solution on other distros is to install a dummy monitor to make debian think a monitor is connected. A solution for debian 9 is described here:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-debian-9

But I'm unable to transfer this solution to slax. What desktop environment is installed on slax and what commands do I have to modify and issue to be able to access vnc on a headless system?

**Comment by Tomas-M** [comment]
This is not related to linux-live project, and I cannot help you with this beyond the information that Slax is using FluxBox as a window manager.
