### ISSUE TITLE
Suggestions on new S.L.A.X version

### ISSUE THREAD

**Issue by tree-t** [Tomas-M/linux-live#190]
Hello Tomas, 
I read on https://www.slax.org/next.php that you are going to create a new version of S.L.A.X in the upcoming months and that you need suggestions from us on bugfixes, etc. The things that I would like to suggest are:
1. Replacement of aufs with overlayfs
2. When hovering over the edges, the mouse should change its icon, as currently it doesn't do the same and makes life tough
3. Make xlunch launch with the use of super key(commonly known as windows key), as a lot of people migrate to Slax from Windows
4. Add a night mode and/or redshift
5. Fix fluxbox reverting to its original state when upgraded, as when the users upgrade it, your patchs are nullified and the ugly ui of fluxbox is revealed
6. Make pcmanfm the default desktop(a simple way is to make 'pcmanfm --desktop' run as soon as fluxbox loads(, as that will allow the user to use fluxbox like any other modern day D.E.'s.

I have, as when I sent it to slax-users@googlegroups.com but I didn't get a reply and wanted you to consider my opinion also.
Regards,
Tree-J

**Comment by tree-t** [comment]
Just found that this is a terrible place to discuss issues. Hence I am closing mine.

**Comment by Tomas-M** [comment]
Thank you very much for your suggestions.
1. this is not possible since overlayfs does not provide all features of aufs
2. unfortunatelly I do not know how to do that
3. this is probably possible and I am willing to do that but currently I do not know how. It will probably require some settings in fluxbox keyboard shortcuts mapping
4. night mode will not be added, I am sorry
5. unfortunately if you upgrade fluxbox, it downloads the Debian's version which does not have the patched features
6. I am actually happy with desktop without icons at the moment, I am sorry :)

**Comment by tree-t** [comment]
Thank you for replying Tomas,
For the 3ʳᵈ one, you can
3. a. Save the script that you use for launching xlunch (lets say you saved it as xlonch)
b. make it executable( chmod +x xlonch)
c. cp xlonch to /usr/bin
d. Allocate windows/super key to fluxbox's config to run xlonch ( just like alt+f1 runs xterm)

**Comment by Tomas-M** [comment]
Sure I know that :) What I do not know is how to bind the Win key alone (it is called Mod4 in fluxbox configuration, but there is only way to bind it to an action while another key is pressed, for example Win+F1 can be configured as Mod4 F1, but if I put just the Mod4 key there, nothing happens.

Xlunch is currently mapped to Alt+F2, which is standard shortcut to "run a new command" in Linux
I could possibly map it to Ctrl+Esc as well, which is a standard shortcut for windows.
But I do not know how to map it to the Win key alone

**Comment by tree-t** [comment]
Hello Tomas,
This time I have an issue and a fix.
Issue: When I was testing out "slax-64bit-11.2.0-rc2.iso", I found that connman was not able to turn the soft switch on for my wifi and I wasn't able to connect to wifi or anything, maybe I will be able to tell you the fix very soon.
Fix: for the Mod4 key, it will somehow not take the super key as Mod4, therefore the fix is, to attach this to the end of 
~/.fluxbox/keys:
 Super_L : Exec fbappselect
I hope it helps.
Bye 
:)
