### ISSUE TITLE
Using linux-live on Fedora/CentOS?

### ISSUE THREAD

**Issue by prp-e** [Tomas-M/linux-live#198]
Just curious about this repository and how can I use it on Fedora or CentOS.

**Comment by Tomas-M** [comment]
It should be universally working everywhere, but you may need some tweaks, fedora is untested by me

**Comment by prp-e** [comment]
Thanks @Tomas-M for the reply. Which distros have you tested and got the results?

**Comment by Tomas-M** [comment]
Debian, Ubuntu and other distros based on those two are tested
