### ISSUE TITLE
Build custom kernel

### ISSUE THREAD

**Issue by thenoobtester** [Tomas-M/linux-live#201]
Hi Tomas,

I'm trying to build a new kernel but failed. I tried using different config files I got on the web since I'm running slax 9 but you removed the build/config files, so I was wondering if you could please share the config file you used for slax 11? I feel as if my kernel won't boot because of something wrong in the config, I never compiled a kernel before so it may be something else. Also I'm compiling it on a google colab machine because my own machine is too weak and I need it to work. Do I have to compile it on Slax?

Thank you for your help.

**Comment by Tomas-M** [comment]
I used config file from Debian, which needs to be updated to enable AUFS (after patching the kernel sources).
There is a script to build kernel for Slax, in ./tools 
I am not sure if the config file for Debian can be found anywhere on the internet, but I think you should be able to get it with

    apt install linux-headers-{{something}}

(look into /usr/src/ subdirectories)
(you may need to use apt seach linux-headers ... to find out what particular package to install

**Comment by thenoobtester** [comment]
Ok, thank you. yes I used your script in tools.

**Comment by Tomas-M** [comment]
I uploaded the config here
https://slax.org/a/config-5.10.0-11-amd64

You may need to do 'make oldconfig' to add configurations for your particular kernel if it has newer options.

**Comment by Tomas-M** [comment]
By the way, you will need to rename the config file to .config 
and put it to your kernel sources dir.

**Comment by thenoobtester** [comment]
Thank you :)
