### ISSUE TITLE
DHCP fails when network booting on 32-bit Alpine Linux

### ISSUE THREAD

**Issue by marcii-101** [Tomas-M/linux-live#202]
When I try to boot the system from the ISO file, it boots correctly, **but** if I try to netboot it i get the following error:
`udhcpc: socket: Address family not supported by protocol`
I am using QEMU 5.2.0 to boot it.
Here's a screenshot:
![netboot-error-32bit](https://user-images.githubusercontent.com/86745494/159154356-b3719511-537d-4e93-866c-03c4342a8adb.png)
I also don't see any HTTP requests in my server logs

**Comment by Tomas-M** [comment]
Most likely there is no network driver for your qemu machine.
Either you didn't specify NETWORK=true in config file, or if you did then you will probably need to modify the initramfs/initramfs_create script, and add a line to include appropriate kernel module

**Comment by marcii-101** [comment]
The image boots over the network if i manually set up the network using the ip kernel argument.

**Comment by Tomas-M** [comment]
Well, the first error says
sh: write error: cannot allocate memory.
Unless you resolve this error, there is no reason to investigate this at all, since you simply do not have enough RAM for the system to work properly.
