### ISSUE TITLE
Linux-live not working in qemu vm

### ISSUE THREAD

**Issue by tree-t** [Tomas-M/linux-live#203]
Hey Tomas,
Today, as I was further expanding a custom OS named S.L.U.X,
I got the following error:
![Screenshot_20220406-184125_VNC Viewer](https://user-images.githubusercontent.com/98072621/162197678-cf9de7c4-648c-48cd-9366-aef5952957d4.jpg)
But I thought that it might be a problem with my wierd tweaks, 
So I tried S.L.A.X 11.3 (x64) in qemu vm(x64)(just to check whether it is a LiveKit problem or not...), but this time also I got a kernel panic:
![Screenshot_20220407-102747_VNC Viewer](https://user-images.githubusercontent.com/98072621/162198168-acb4d956-94f8-4664-bd54-f140f4aa79ca.jpg)

My Qemu-system-x86_64 version: 
![Screenshot_20220407-180042_Termux](https://user-images.githubusercontent.com/98072621/162199028-3daf746e-9e59-4abc-b667-07be1902be0f.jpg)

Thanks in advance
~Tree-T

**Comment by Tomas-M** [comment]
It seems like you did not configure qemu correctly so it does not load initramfs.

**Comment by tree-t** [comment]
Thank you @Tomas-M ,
After you wrote the following comment:


> It seems like you did not configure qemu correctly so it does not load initramfs.

I found out that my command didn't include:

`-m  500m`

~Tree-t
