### ISSUE TITLE
Initramfs inpacking failed: junk at the end of compressed archive

### ISSUE THREAD

**Issue by narf99** [Tomas-M/linux-live#206]
when ever I boot to the usb I made I get this error. booting through legacy boot. I setup the usb on a manjaro laptop I had to update the config file but I didn't run isolinux.bin.update idk if that's my problem
![20220419_083630](https://user-images.githubusercontent.com/53348921/164040114-1430ef73-192c-4c96-b6df-fb8c1e0d51e1.jpg)
.
this is the output that I get when I boot in normal mode (not debug mode)

**Comment by Tomas-M** [comment]
Hello. The error message - unable to mount root fs - that means it didn't find your initrd (initrfs.img file)
I would say that either your bootloader configuration is not properly set so it gets not loaded, or you are missing the file. It should be in the same directory as vmlinuz

**Comment by narf99** [comment]
And how do I change the bootloader configuration lol?

**Comment by narf99** [comment]
if I try and open the initrfs.img file on windows it says the disk image file is corrupted. On Linux it only shows the initrfs file and that's on the actual output of Linux live kit not the zip from the command.
