### ISSUE TITLE
fstab problem with linux-live-kit 2.6

### ISSUE THREAD

**Issue by Littlebigone** [Tomas-M/linux-live#208]
Hi Tomas and all,

I found another problem running linux-live-kit on ubuntu. When running the zip kit in persistant changes, any change made to fstab are lost at next boot. Any other changes on the system persists but not for the fstab. The fstab seems to be overwritten at every boot.

I discovered it because I need to mount a partition /home living on another disk and I would like also to set it in the fstab.

Usually I also set some directories into tmpfs to speed-up the system, /tmp and /home/user/.cache so they reside in RAM and will be lost at shutdown because we usually don't care about cache and temporary files.
Can someone confirm it is still useful in linux-live-kit running aufs ?

Thanks in advance.
Laurent CAS

**Comment by Tomas-M** [comment]
I can confirm that fstab is reset on each boot, because it is assumed that you are booting the system on different computers with different disks. I will think about improving this functionality somehow
