### ISSUE TITLE
Running live kit 2.6 in FAT32

### ISSUE THREAD

**Issue by Littlebigone** [Tomas-M/linux-live#209]
Hi Tomas and all,

When running a linux live kit made with linux live kit v2.6 on a FAT32 pendrive it comes a time when I have an error message saying 'disk full'. The 32Go pendrive is not full but the changes file has reached the 4Go limit. I would have think linux live kit chain the 4Go file to another one and so on...
Am I wrong ?

**Comment by Tomas-M** [comment]
Unfortunately changes bigger than 4GB is not supported on FAT filesystem at the moment, I am sorry
