### ISSUE TITLE
Tar files errors in linux-live

### ISSUE THREAD

**Issue by Littlebigone** [Tomas-M/linux-live#211]
Hi Tomas and all,

In Linux-live-2.6.tar, when extracted the following files are unmatched:

linux-live-2.6/Slax/debian11/modules/02-xorg/rootcopy/etc/systemd/system/display-manager.service

linux-live-2.6/Slax/debian9/rootcopy/etc/systemd/system/multi-user.target.wants/dhclient.service

linux-live-2.6/Slax/debian9/modules/04-apps/rootcopy/etc/systemd/system/suspend.target.wants/resume_wifi.service

linux-live-2.6/Slax/debian9/modules/02-xorg/rootcopy/etc/systemd/system/display-manager.service

The debian10 is not there anymore but it was in previous linux-live and the
problems were the same.

It seems your tar captured the symlinks instead of the real files.

Best regards

**Comment by Tomas-M** [comment]
Well, it is because the links are absolute.
This is not an error. Probably the target files are not on your system, but that doesnt matter
