### ISSUE TITLE
QUESTION: use on encrypted system.

### ISSUE THREAD

**Issue by Rodgers13** [Tomas-M/linux-live#212]
Hello, I was wondering if I can use this on my system. While installing KDE NEON I chose to encrypt the system. Can I still use Linux-Live to make my custom distro or will the fact that i encrypted on install not make this possible?

Thanks

**Comment by Tomas-M** [comment]
I am not sure on what level do you encrypt your filesystem, but liveKit is a set of scripts which you extract somewhere and it will access your files as any other process, so I would say encryption does not matter here. The resulting live system will not be encrypted
