### ISSUE TITLE
Operating System not found

### ISSUE THREAD

**Issue by pankajmalhotra** [Tomas-M/linux-live#216]
Hi,

kernel version: 5.4.0-110-generic
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

Followed following steps:
1. downloaded the wget https://github.com/Tomas-M/linux-live/archive/v2.6.tar.gz
2. untar
3. updated config file to "/boot/vmlinuz"
4. Ran isolinux.bin.update under tools
5 copied files to ~/linux-live-2.6/bootfiles
6. executed ~/liux-live-2.6/build
7. /tmp/gen_linux_iso.sh
8. Iso file was generated.

9. Created a VM with mountable boot from iso image.
10. Rebooted the VM, disconnected CD. It says no operating system found.

Let me know if I missed any step.

Thanks,
Pankaj

**Comment by tree-t** [comment]
Hello @pankajmalhotra,
1. Can you please provide a screenshot of the error?
2. Can you make an iso without performing step 2 and 3 on a fresh(unmodified) version of linux-live-kit?
3. Can you try using the iso on real hardware?( So as to verify that the iso is bootable or not)
~Tree-t
:)

**Comment by pankajmalhotra** [comment]
Hi @tree-t ,

1. As far as screenshot is concerned, once I reboot the VM without iso, it doesn't come up.
2. 

- without updating config file, it doesn't build also
```
root@sjcvlbldub2042:/linux-live-2.6# ./build                
Changing current directory to /linux-live-2.6
Building initramfs image...
cp: cannot stat '/vmlinuz': No such file or directory
```

if I edit the config file "/boot/vmlinuz", everything comes up, but once I reboot without linking iso, it doesn't do that.

4. Currently running on real hardware is not possible, unless VM works.

Let me know if I have missed something
Thanks,
@pankajmalhotra

**Comment by tree-t** [comment]
Hello @pankajmalhotra ,
1. Can you try using qemu as the vm? As mostly if the iso is bootable the vm will work(in qemu)

For qemu you have to:
1. Install it( on ubuntu , in a terminal):
```
sudo apt install qemu-common qemu-system-gui
```
2. Change the directory to the working directory (where the iso is stored)
3. Run the vm:
```
qemu-system-x86_64 -m 1G -cdrom *.iso
```
Note: Replace *.iso with the iso name.
Breakdown of command options used:
```-m``` is used for allocating memory to the vm . 1G means 1GB, for `mb` use `-m` . eg:
 ```
-m 1m
```

If everything was fine, then the iso will boot normally.
~Tree-t
:)
