### ISSUE TITLE
Netplan by default in 17.10

### ISSUE THREAD

**Issue by Bindea** [Tomas-M/linux-live#22]
https://insights.ubuntu.com/2017/07/10/netplan-by-default-in-17-10
http://cdimage.ubuntu.com/daily-live/current/

Just installed the latest daily build and everything worked perfectly but when i made an ISO with Linux_live i had no network connection , i don't know if it's anything to do with the above News that they have added netplan?

Anybody else have the same problem and does anyone have a work around?

As 17.10 is still Alpha testing it's pointless Tomas adding a fix to the script as they might change things again by the time it's released.

Thanks

**Comment by GamerBrownie2** [comment]
#28
