### ISSUE TITLE
cannot boot

### ISSUE THREAD

**Issue by lentas1** [Tomas-M/linux-live#221]
![image](https://user-images.githubusercontent.com/88710364/173232062-c30967dd-dd33-45a3-8e2c-0971b57ce6cd.png)

**Comment by lentas1** [comment]
It says "idlinux.c32 not found", but i check iso, then it founds

**Comment by lentas1** [comment]
but i cannot boot

**Comment by lentas1** [comment]
![image](https://user-images.githubusercontent.com/88710364/173282785-f3568586-34d7-4425-92b5-31e18bbcf8fd.png)

**Comment by qiang-yu** [comment]
There is a bug which did not fix for several months
 
The Bug is 

DO NOT CHANGE THE NAME  in  config   LIVEKITNAME

Although the document says you can  change this name  and re-build isolinux , 

The fact is that ,  if you change the name, your ISO  would never boot , never ...

do not change that name, and build your iso, everything works fine

**Comment by WhiteBlackGoose** [comment]
Having the same issue. OP, please next time mention some keywords in title or text. What we're getting here is
> Failed to load ldlinux.c32

Related issues: #149 #158 #41 #48 #62 #91 #95 

Basically here's a sum up of what you might consider when hitting this problem:
1. No EFI support
2. Ensure to run `./tools/isolinux.bin.update` script after you changed the LIVEKITNAME variable in the config

My problem though is that this script eventually requires you to insert a disc - which I believe is not what I want, right? I need an iso image. Or am I confused?

**Comment by lentas1** [comment]
> [<img alt="@Tomas-M" width="20" height="20" src="https://avatars.githubusercontent.com/u/2259370?s=40&amp;v=4">](/Tomas-M) [Tomas-M](/Tomas-M) closed this as [completed](/Tomas-M/linux-live/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [Jul 31, 2023](#event-9964845422)
> [<img alt="@lentas1" width="40" height="40" src="https://avatars.githubusercontent.com/u/88710364?s=80&amp;v=4">](/lentas1)

i dont understand what to do
