### ISSUE TITLE
mergerFS request

### ISSUE THREAD

**Issue by Littlebigone** [Tomas-M/linux-live#222]
Hi, 
By now Live-Kit support overlayFS and aufs but overlayFS is too slow to act as a viable replacement for aufs. Installing aufs requires compile, either the whole kernel or the module aufs. But because of distributions dropped aufs support, it is more and more complicated to rely on aufs, and I have been testing a *lot*. MergerFS seems to be a reliable solution, active project, much faster than overlayFS and as good as aufs, and it is officially supported by many linux distributions. 
Please, could you add support for mergerFS as an alternative to aufs ? https://github.com/trapexit/mergerfs
Many thanks for your work.

**Comment by cws999** [comment]
@[Littlebigone](https://github.com/Littlebigone)

You can try
edit  "linux-live-master/initramfs/initramfs_create" 
add a line
"copy_including_deps /$LMK/kernel/fs/mergerfs"

sed -i 's/overlay/merger/g' linux-live-master/livekitlib
