### ISSUE TITLE
Possible memory leak at gen-linux-iso.sh?

### ISSUE THREAD

**Issue by agoodfellow123** [Tomas-M/linux-live#229]
Hello I had an iso that i wanted to create that was little over 4GB so I enabled the -allow-something-something flag (I'm sorry I don't remember the name of the flag) in the gen-linux-iso.sh. Process started to run with no errors at start but at %50 my DE crashed. So I opened tty and checked top. Top said only few hundreds of memory available. But I gave my virtual machine 8GB of ram. I tried running it again from tty after like %67 it crashed tty and now I can't even log in. I'm assuming that's a memory leak.

**Comment by equetzal** [comment]
First, you should try to provide all the context and accurate data when opening an issue (like not providing the flag name, it is important to understand your issue)
Now, maybe this answer is late haha, but what gen-linux-iso.sh does is to run `mkisofs` as you can see on this line:
https://github.com/Tomas-M/linux-live/blob/master/build#L81-L84
So, if you're worried about memory leak, the best would be post the issue on their project (which i'm not sure where they are). 
Now, most likely thing is that your VM is running out of memory. Just increase the amount of RAM and you should be fine, but who knows, there's not enough context for knowing the specific problem.

**Comment by computermaster0101** [comment]
I've experienced similar when the sb size exceeds the amount of ram available.  If your including a file larger than 4gb it's possible you need more than 8gb
