### ISSUE TITLE
linux-live: Bundles

### ISSUE THREAD

**Issue by opselo** [Tomas-M/linux-live#233]
Hello Tomas,
I am a Slax lover since time immemorial. Thank you very much for this hard work.

I have a question, I'm new using linux-live. I have created an ISO with the linux-live (without using scrips of the directory /slax of the repository); ISO starts and works perfectly. It is a Core of Debian 10.13. Now the question:

* When we use the scripts (no-slax), it obviously does not have advanced capabilities [Savechanges, activate modules in execution time, etc]. But can you do something to save a bundle and then load it by restarting? Or is it too late for this?

* With the ISO that I tell you, I can create a Bundle (SSH-client) via CMD with Squashfs (I do not use the Savechanges script of Slax). When restarting the Log says that the modules have been loaded [01-core.sb and 02-SSH-client.sb], but nothing is injected into the system. I have tried both in/linux/02- .. and in /linux/modules/02- .. How can I get this?

I speak of CMD after starting, not to modify the behavior of ISO. The ISO was from a fresh installation, without trimming, and executing only the Build.sh (only Zip, Genisoimage and Squash were installed).

Thanks.

**Comment by equetzal** [comment]
Not Tomas, but this might help to close this issue. 
Yes, when you use no-slax build scripts you still being able to create a new bundle. You can just use the savechanges script to save the changes. But if you are trying to create your own bundle, take in consideration that the way is which is being compressed might be 'special'. Here you can see how this is being done in the dir2sb script. 
https://github.com/Tomas-M/linux-live/blob/64247368a633d07f10f1dbef251071a63c19cf5a/Slax/debian11/rootcopy/usr/bin/dir2sb#L47
Now, I would tell you that this exact script (dir2sb) is enough for achieve the task you're looking for. 
Also, depending on the name you have chosen for you live-kit the directory to put your bundle is /<name>/, and remember they're being mounted on the root of your file system. 

Also, once you've booted you can look into the /sys/fs/aufs directory to lookup for all the branches mounted. 
I've also created a tool named 'auls' (for AUFS list) for listing all the current branches (layers) loaded into your filesystem.
https://github.com/equetzal/huronOS-build-tools/blob/main/base-system/usrroot/usr/sbin/auls

If there's the case in which your branch stills not being mounted, you'll be needing to debug you initramfs to know the reason why it is not being loaded (probably mount command is failing or something like that).

**Comment by opselo** [comment]
@equetzal Apparently, this is just i need. Thanks a lot.
