### ISSUE TITLE
Use encryption on boot

### ISSUE THREAD

**Issue by anoskar** [Tomas-M/linux-live#234]
Hi, 
is it possible to use system boot encryption? 
I would like to boot my system and provide the os decryption key like another linux os 
For example 
My ubuntu boot and he ask me my password for decrypt my FS partition. 

Thank you

**Comment by Tomas-M** [comment]
I am not sure what is your goal.
Do you want to encrypt the live operating system so it only starts after a correct password is provided?
This is currently not supported
