### ISSUE TITLE
Unable to boot after powerloss

### ISSUE THREAD

**Issue by computermaster0101** [Tomas-M/linux-live#236]
Hey Tomas! It's been a while! I have a new issue I've been unable to resolve. If disk activity is happening and the system is halted I'm unable to boot until I run chkdsk over the volume in windows.  

Any thoughts on how I might get around this?  I added fsck.mode options to the syslinux.config but had no success preventing the issue.  I'm using a ntfs partition. Should i use a different partition type?

**Comment by Tomas-M** [comment]
Is this related to your own live system, or to Slax in particular?
How do you halt the system?
Basically for your own live system, you need to ensure that the shutdown procedures are called on shutdown, you need to ensure that the script in /run/initramfs/shutdown is called. In Debian this is done automatically by systemd, or at least it should be.

**Comment by computermaster0101** [comment]
Ok, this has more to do with the file system type. Ext4 is more resilient to sudden power outage. Used fat32 for booting and ext4 for data.
