### ISSUE TITLE
Not bootable on Ventoy

### ISSUE THREAD

**Issue by mcut17198** [Tomas-M/linux-live#238]
I generated an ISO and copied it into my USB stick with Ventoy installed. When trying booting this ISO, it stuck with `Looking for lovely-livecd data in /lovely-livecd ...`
About one minute later, it shows that 
```
Fatal error occured - Could not locate data
Something went wrong and we can't continue. This should never happen.
Please reboot your computer with Ctrl+Alt+Delete ...
```
Any solutions?

**Comment by computermaster0101** [comment]
I use easy2boot without issues.  This may be related to the drives included. You might need to add additional drivers for the USB. 

Here are some troubleshooting steps I did:
https://github.com/Tomas-M/linux-live/issues/133#issuecomment-1056049583

**Comment by newbie-c** [comment]
Guys, I think this iso-image is not hybrid, it can be booted only from CD/DVD, no USB stick, no Ventoy. If you want a bootable USB-stick follow the actual procedure the author gave you in README - it works.

**Comment by cws999** [comment]
> 
@newbie-c 
There are a few lines in the readme
“If you want to use the Live Kit on a USB you have to either
  - use Windows to execute the bootinst.bat file in the $NAME/boot folder
  - or use Linux to execute the shellscript bootinst.sh in the $NAME/boot folder”

But I can't find  bootinst.sh

**Comment by newbie-c** [comment]
Actually, it is there. Here is the picture how it looks on my desktop.
![picture](https://codej.ru/picture/O7TgOK5F0S.png)
