### ISSUE TITLE
Can not poweroff

### ISSUE THREAD

**Issue by qiang-yu** [Tomas-M/linux-live#240]
I use this project to make a Ubuntu 22.04 as live disk

live disk boot oK,  but can not poweroff

poweroff / halt -p / shutdown -h now / init 0   all turn to reboot, 
i can not poweroff the system unless i cut the power physically

is there any solution to this problem ?

thanks

**Comment by newbie-c** [comment]
https://github.com/Tomas-M/linux-live/issues/230
