### ISSUE TITLE
genisoimage: Uh oh, I cant find the boot catalog directory '<name>/boot'! error

### ISSUE THREAD

**Issue by ChunkyZacko5** [Tomas-M/linux-live#243]
Hello, i was generating my ISO file that my Linux distribution is competed. I got that:
![Screenshot from 2023-01-01 04-31-33](https://user-images.githubusercontent.com/111050027/210159562-1171f2d8-daa6-4c88-9612-d5be8e232326.png)
`genisoimage: Uh oh, I cant find the boot catalog directory 'cubuntu/boot'!`
I need to generate my ISO... 😢

**Comment by Tomas-M** [comment]
I am afraid I do not know how to fix this, sorry
