### ISSUE TITLE
Install Live Linux

### ISSUE THREAD

**Issue by ashayesteh86** [Tomas-M/linux-live#244]
Dear All 
How can I Install New Linux after creating and starting live?

**Comment by Tomas-M** [comment]
The point is to run it as Live OS, without the need of installation :)

But basically, to install any Linux in general:
- run your live OS
- create on-disk partition with some Linux filesystem (eg. ext4, xfs, ...)
- copy everything from / to your partition (except mounted directories such as /proc or /sys of course, just mkdir these)
- make it bootable somehow (eg. chroot to your partition, mount /proc and /sys there, setup grub)
