### ISSUE TITLE
how to install it to a different target HDD or SSD?

### ISSUE THREAD

**Issue by Shibaditya99** [Tomas-M/linux-live#245]
Created the live linux USB. But it's need to install on the target device after booting up from USB. So is there any option is available?

**Comment by newbie-c** [comment]
I think Calamares (you can google it) could be one of possible options. But I'm not quite sure... At least, official Debian Live iso uses Calamares as an installation scenario. CtlOS (you can google is) uses Calamares as well.

**Comment by equetzal** [comment]
> Created the live linux USB. But it's need to install on the target device after booting up from USB. So is there any option is available?

That is not the purpose of this distro. If what you need is to modify an installation, and then pack it as an ISO to restribute it / install it anywhere else, then you can use any other tool for iso packing and resdistribution.

**Comment by nossila2** [comment]
Are there any tool suggestions for this? I need to perform the installation from the generated ISO.

**Comment by computermaster0101** [comment]
I've worked on this a bit and ran into some issues that I couldn't get past mainly programmatically formatting the target drive correctly is what stopped me from continuing down that path.  Instead I have to manually install onto target drive

**Comment by nossila2** [comment]
The situation I need to solve: Install an ubuntu with SSH installed by default to later execute commands via Ansible. Ubuntu does not install SSH by default. If you know of any way for this case. Thanks.

**Comment by equetzal** [comment]
> Are there any tool suggestions for this? I need to perform the installation from the generated ISO.

You can use https://github.com/antiX-Linux/iso-snapshot, there's a lot of tools for doing this, but this one have a decent UI.

**Comment by Tomas-M** [comment]
As [equetzal](https://github.com/equetzal) said, that is not the purpose of this tool. Closing
