### ISSUE TITLE
DVD not picked up as bootable

### ISSUE THREAD

**Issue by Lepps01** [Tomas-M/linux-live#247]
Hi all. I'm able to use the build scripts to generate an ISO file of a customized Ubuntu instance. I can run the install script on a USB that makes a USB work without an issue. I try and burn the ISO to disc using Windows (right cick ISO file - burn to disc) and the DVD is not picked up by a number of different PCs as UEFI bootable. 

What am I missing?

**Comment by Tomas-M** [comment]
The ISO does not have any special handling for UEFI boot. Please try to boot it using regular (old) bios boot mode.
If you know what is needed to modify liveKit to support UEFI boot from CD, feel free to submit patches.
Thank you
