### ISSUE TITLE
Creating 4.0 filesystem - 01-core.sb (stuck at 106 bytes)

### ISSUE THREAD

**Issue by jupgithub** [Tomas-M/linux-live#249]
Hi,
I have been trying to make a linux live from my Mint 20.3 system without success.
Every time, the terminal stays at : Creating 4.0 filesystem ... 01-core.sb (it stays at 106 bytes)

I don't know what is happening in my system.

Thanks for your help.

**Comment by Tomas-M** [comment]
I don't know neither, maybe you are running out of disk space or memory
