### ISSUE TITLE
usb boot failed to use vesamenu.c32

### ISSUE THREAD

**Issue by GreggJensen** [Tomas-M/linux-live#25]
I am using the latest code from GitHub and created a usb following the instructions and when the usb it put into the target machine it responds with failed to use /.../boot/vesamenu.c32.  It looks like it found it ok, just couldn't use it.  I have confirmed that the file is there, and that the version is 4.06 (as a post on another site said to use).  That version is in the latest source code.  At a loss for troubleshooting this issue, any thoughts?

**Comment by Tomas-M** [comment]
I am in the process of implementing new changes and latest code from github may be broken sometimes. Please stick to stable release or wait until it gets fixed in master branch. I remember having similar issue so I guess it should be fixed, you can try now. Thank you
