### ISSUE TITLE
cp: -r not specified; omitting directory '/boot'

### ISSUE THREAD

**Issue by michael-clarke** [Tomas-M/linux-live#257]
I am trying this for a running Oracle Linux 9.2.  I have change the config file such that VMLINUZ=/boot however when running the build script I get the following error.

`# ./build
Changing current directory to /tmp/linux-live
Building initramfs image...
cp: -r not specified; omitting directory '/boot'`

Not sure how to proceed now.  Thanks for the help.

**Comment by Tomas-M** [comment]
The VMLINUZ variable should point to the actual vmlinuz file, not a directory
