### ISSUE TITLE
Is is too complicated to implement a boot password and/or implement this script in an encrypted install?

### ISSUE THREAD

**Issue by robertocarloar** [Tomas-M/linux-live#258]
Since unsquashing modules can be done on the fly using AUFS or manually with overlay, all relevant information regarding the later added user data is therefore open.
Thank you.

**Comment by Tomas-M** [comment]
I am afraid that I do not understand the question.
Are you interested in password-protected storage for persistent changes? Or do you want to password-protect even the data inside squashfs modules?

**Comment by robertocarloar** [comment]
I meant both: Using the script to create a live environment on an encrypted partition and/or encrypt modules. Thank you

**Comment by Tomas-M** [comment]
To me it is too much complicated.
The same result can be achieved by hardware device such as Kingston DataTraveler DT2000
