### ISSUE TITLE
Tomas is suddenly active with the script?

### ISSUE THREAD

**Issue by Lucapz** [Tomas-M/linux-live#26]
Tomas has been active the last few days adding and removing code , anyone know what he is up too?

Is it just general fixes or are there new changes about to happen?

Thanks

**Comment by Bindea** [comment]
@Tomas-M 

http://linuxiumcomau.blogspot.com/2017/06/customizing-ubuntu-isos-documentation.html

Just found this other rather complex script , don't know if any of the code is of use to you?

**Comment by Tomas-M** [comment]
@Lucapz
I am currently working on new Slax based on Debian.

@Bindea 
the link you mentioned is not related to me

**Comment by Lucapz** [comment]
@Tomas-M

A couple of questions about the new Slax based on Debian.

1) If you have multiple webrowser windows open will there be a hover preview window when you pass your mouse over them?

2) Will it be easy to add Debian security updates as that function seems to be rather lacking on other live disk projects or it's way too complicated for a new Linux user.

Thanks

**Comment by Tomas-M** [comment]
1. no
2. manually, if you know what you are doing, yes.

**Comment by Lucapz** [comment]
It would be nice if you could add a easy one click update option for security otherwise it will leave newbies in a vulnerable position with online banking and such.

openssl bugs that keep turning up as an example.

**Comment by Lucapz** [comment]
Has anyone tried the Live script with an Arch Linux install?
