### ISSUE TITLE
Slax will not boot from NTFS.

### ISSUE THREAD

**Issue by crim50n** [Tomas-M/linux-live#260]
Slax will not boot from NTFS. Slax will not boot from NTFS. Perhaps it makes sense to revert to the old option with @mount.ntfs-3g?
![slax](https://github.com/Tomas-M/linux-live/assets/16401199/4e8ba4ab-4c70-4747-8aaf-3b6a37df524b)

**Comment by Tomas-M** [comment]
Actually, Slax will work from NTFS, if you manage to make it boot from it (load vmlinuz and initramfs)
But if your NTFS partition is marked as dirty (not properly unmounted), it will not "find it".

**Comment by crim50n** [comment]
I created a partition, formatted it to NTFS, mounted it, copied slax, installed the bootloader, unmounted and rebooted the virtual machine. From inside initrd I can't mount with ntfs3, but have no problem mounting with ntfs-3g, which also won't mount a dirty filesystem, which means it's clean.
