### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by tarokeitaro** [Tomas-M/linux-live#270]
I made it bootable for my custom linux. but I can't boot into the system. it will keep repeating itself.
I had another project, but it booted successfully. is there a problem if I use RTLinux? all my projects use debian12

`/LiveDSP/boot/initrfs.img...failed: I/O error`

![image](https://github.com/Tomas-M/linux-live/assets/42670754/89862f8b-4ca9-4c9b-9c18-f1459b6bcd4d)

**Comment by tarokeitaro** [comment]
After I compared my two projects. I realized that initrfs.img doesn't contain anything. is there any hint?

![image](https://github.com/Tomas-M/linux-live/assets/42670754/d5e4cc49-2a01-4ffa-bccf-c0d9bd6b09f9)

**Comment by neogopher98** [comment]
It was also solved by installing xz-tools

**Comment by Tomas-M** [comment]
Thank you for reporting this, I should add there a check for xz in order to stop if it's not installed.
