### ISSUE TITLE
could not find Linux data - Debian Bookworm

### ISSUE THREAD

**Issue by man-schu** [Tomas-M/linux-live#272]
I am using Debian Bookworm. I install the basic system with Debian Netinstall and then install the rest via apt.

Linux Live boots with Ventoy in legacy mode, which would be totally sufficient for me, but then it does not find the file 01-core.sb, saying "could not find Linux data". This is when I keep the default LIVEKITNAME. When I adapt the LIVEKITNAME, it is even worse. It says "Failed to load ldlinux.c32.

**Comment by crim50n** [comment]
Custom distributions built with Live Kit will not work in Ventoy, as you will need to modify the Ventoy source code to add support for your distribution.

**Comment by man-schu** [comment]
As far as I know, there is a way to make your iso file Ventoy compatible, as explained here: https://www.ventoy.net/en/doc_compatible_mark.html. 

As it is a quite cumbersome procedure, it would make sense to integrate the necessary steps in the linux-live scripts.

This would, by the way, make linux-live even more attractive, as Ventoy is about to become a quasi standard, as you need to carry less USB sticks with you.

**Comment by Tomas-M** [comment]
Marking the ISO as compatible will not make Slax compatible with Ventoy.
There is a pull request for ventoy support already so I will review it to see if this is going to be added or not.

**Comment by man-schu** [comment]
Thank you. Appreciate your work. 👍

**Comment by crim50n** [comment]
> Маркировка ISO как совместимого не сделает Slax совместимым с Ventoy. Уже есть запрос на вытягивание для поддержки ventoy, поэтому я рассмотрю его, чтобы увидеть, будет ли он добавлен или нет.

Tomas, Slax is already compatible with Ventoy, but distributions built by users default to the `linux` folder name, not `slax`, because of this Ventoy support does not work.

**Comment by man-schu** [comment]
I tried the following:
I entered LIVEKITNAME="slax" in the config file. Then upon executing tools/isolinux.bin.update, I chose /slax/boot.
The result is still the same. It tells me: Failed to load ldlinux.c32

**Comment by crim50n** [comment]
> I tried the following: I entered LIVEKITNAME="slax" in the config file. Then upon executing tools/isolinux.bin.update, I chose /slax/boot. The result is still the same. It tells me: Failed to load ldlinux.c32

Unfortunately, I can't help you with that. Try running the original Slax in Ventoy and see if it works there now. This will help you figure out what direction to take next.
