### ISSUE TITLE
No connection in Ubuntu 17.10

### ISSUE THREAD

**Issue by GamerBrownie2** [Tomas-M/linux-live#28]
When you create an ISO with the builder and then boot it
you don't have an internet connection

**Comment by Tomas-M** [comment]
Possible cause is that you're booting different kernel version than the modules you have included in /lib
After booting your Live CD, check uname -a, and /lib/modules/ version

**Comment by GamerBrownie2** [comment]
They are both the exact same version

**Comment by Tomas-M** [comment]
Thanks for the info. In that case I do not have any other idea what could be wrong, as long as you have the same filesystem, you should have the same functionality. I'd suggest you to firstly check if the network driver is loaded (lsmod) and if not then try to load it manually (modprobe). Other than that, I would check if network can be configured manually (ifconfig) or by dhcp (dhclient).

**Comment by GamerBrownie2** [comment]
The driver is loaded and i already tried configuring manually, and it is trying to connect, but then it fails after about 10 seconds

**Comment by Tomas-M** [comment]
manually, you mean by setting IP address of your choice, or by contacting DHCP server?

**Comment by GamerBrownie2** [comment]
Setting a custom IP and DNS

**Comment by Tomas-M** [comment]
Are you booting it on the same computer where you built it?
How many network adapters you have?

**Comment by GamerBrownie2** [comment]
one network adapter (connected with cable), built with the same computer

**Comment by Tomas-M** [comment]
This would eliminate a possible problem with persistent udev rules which would rename your adapter (like eth0 -> eth1). In this case, I am really sorry I cannot help you, since I literally have no other idea. Is your ISO too big? Can  you upload it somewhere so I could get it and test myself?

**Comment by GamerBrownie2** [comment]
It is just 1,1 GB big, i will upload it and then send the link

**Comment by GamerBrownie2** [comment]
And i will look if it happens with ubuntu 16.04.3

**Comment by Lucapz** [comment]
https://github.com/Tomas-M/linux-live/issues/22
