### ISSUE TITLE
I want my Slax

### ISSUE THREAD

**Issue by alexandre-mbm** [Tomas-M/linux-live#30]
Hello, @Tomas-M! I want to customize my Slax. I need to learn to create bundles. Where I can read about it?

I want auto adjusts sush as:
- Timezone / Today I use `dpkg-reconfigure tzdata`
- Language / Could I try the old bundle Brazilian-Portuguese?
- Keyboard / Today I use `setxkbmap br abnt2`
- Copy to RAM by default
- `passwd` when booting...

I also want to install packages by using `apt`:
- `xtrlock`
  - Config
  - Shortcut

And extensions on Internet browser.

And security private issues.

Thanks.

**Comment by milo** [comment]
You can start by [savechanges](https://github.com/Tomas-M/linux-live/blob/7dcb58b501e319b6e6b49bc702b665d466d35420/Slax/debian/rootcopy/usr/bin/savechanges) script.

In short:
- make changes in filesystem as you wish
- review them in `/run/initramfs/memory/changes`
- call `savechanges my-module.sb`

**Comment by alexandre-mbm** [comment]
Your solution is amazing! And today I also know about [Buildscripts](http://www.slax.org/blog/19604-Buildscripts.html) and templates.

**Comment by alexandre-mbm** [comment]
Tip: for more info see [blog](https://www.slax.org/bs/blog.php).

**Comment by alexandre-mbm** [comment]
@milo, savechanges saves browser cookies and passwords! This is dangerous.

**Comment by Tomas-M** [comment]
This is intended behavior

**Comment by alexandre-mbm** [comment]
If there was a way to encrypt...

**Comment by Tomas-M** [comment]
patches welcome :)

**Comment by alexandre-mbm** [comment]
Almost ready to brazilian users!

![menu](https://user-images.githubusercontent.com/957501/33747332-27308986-dba1-11e7-9c84-d641c590545c.png)

![bar](https://user-images.githubusercontent.com/957501/33747329-26dbac72-dba1-11e7-8402-61fc45ebd78b.png)

![chromium](https://user-images.githubusercontent.com/957501/33747330-2700fa54-dba1-11e7-98ba-62d22333b47f.png)

![xlunch](https://user-images.githubusercontent.com/957501/33747333-274ac422-dba1-11e7-9ca3-0365276c8f97.png)

![logout](https://user-images.githubusercontent.com/957501/33747331-2718735a-dba1-11e7-8ede-222d03dba4bf.png)

![leafpad](https://user-images.githubusercontent.com/957501/33747444-c887af9e-dba1-11e7-9175-b11217d0c218.png)

**Lacks the Qalculate ONLY...**
