### ISSUE TITLE
No sound with snd-hda-intel

### ISSUE THREAD

**Issue by alexandre-mbm** [Tomas-M/linux-live#34]
Looks all okay but no sound! alsamixer shows all unmuted. ALC268 card. I've tried some "options" for the module but no effect.

**Comment by alexandre-mbm** [comment]
How to prepare the Slax to build from Realtek's sourcecode?

**Comment by alexandre-mbm** [comment]
I almost got there by installing Debian build dependencies. However the `make` brokes for `asm/semaphore.h`.  I don't know how this is on Linux kernel 4.9. It does not appears that it is at `asm/semaphore.h` to patch...

**Comment by alexandre-mbm** [comment]
https://code.launchpad.net/~ubuntu-audio-dev/+archive/ubuntu/alsa-daily/+packages

**Comment by alexandre-mbm** [comment]
[Realtek High Definition Audio Codecs](http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=24&PFid=24&Level=4&Conn=3&DownTypeID=3&GetDown=false#2)

**Comment by Tomas-M** [comment]
I don't know how to help with this so I'm closing

**Comment by alexandre-mbm** [comment]
Maybe it is a physical problems. For now I am using SoundWire to send the audio to my phone's speakers.

The Arch Linux from hard drive also is not playing sounds via the laptop's speakers. But it is rolling release and upgraded with the upstreams, then I think that this problem came after I changed the external power supply. I remember of electrical noises on speakers...
