### ISSUE TITLE
Boot trouble

### ISSUE THREAD

**Issue by felmur** [Tomas-M/linux-live#35]
Hi,
I've used your kit to create my own live image using VirtualBox.
At first, I've created a new virtual machine, then I've installed ArchLinux using the Arch-Anywhere tool. Result was a fully functional installation of Archlinux with Plasma KDE Desktop.
After this, I've downloaded your tool (git version) and I've tried to create my distro. After few try I got an ISO of 3.5 Gbyte.

So, I've created another Virtual Machine with cdrom pointed to that linux-x86_64.iso.

At boot, I've see a yellow screen with a Penguin on the left and the classical grub menu. So, I've select ed "Linux" and the boot has started.

After 1-2 seconds, it seems to search something into "linux", but after 30 secs, it stops and the following error got displayed (see the attached image).

I've mounted ISO file. I've found "linux" directory and "readme.txt" file.
In linux dir, I've found 

totale 3636104
-rw-r--r-- 1 root root 3723362304 15 dic 19.49 01-core.sb
drwxr-xr-x 2 root root       4096 15 dic 19.34 boot
drwxr-xr-x 2 root root       2048 15 dic 19.34 changes
drwxr-xr-x 2 root root       2048 15 dic 19.34 modules

./boot:
totale 5655
-rwxr-xr-x 1 root root    1179 15 dic 19.34 bootinst.bat
-rwxr-xr-x 1 root root    1278 15 dic 19.34 bootinst.sh
-rw-r--r-- 1 root root    7336 15 dic 19.34 bootlogo.png
-rwxr-xr-x 1 root root  221776 15 dic 19.34 extlinux.exe
-rw-r--r-- 1 root root      32 15 dic 19.34 initrfs.img
-rw-r--r-- 1 root root   40960 15 dic 19.34 isolinux.bin
-r--r--r-- 1 root root    2048 15 dic 19.52 isolinux.boot
-rw-r--r-- 1 root root  116552 15 dic 19.34 ldlinux.c32
-rw-r--r-- 1 root root  181944 15 dic 19.34 libcom32.c32
-rw-r--r-- 1 root root   23628 15 dic 19.34 libutil.c32
-rw-r--r-- 1 root root     440 15 dic 19.34 mbr.bin
-rw-r--r-- 1 root root   46909 15 dic 19.34 pxelinux.0
-rw-r--r-- 1 root root     435 15 dic 19.34 syslinux.cfg
-rw-r--r-- 1 root root  126511 15 dic 19.34 syslinux.com
-rw-r--r-- 1 root root  243712 15 dic 19.34 syslinux.exe
-rw-r--r-- 1 root root   26684 15 dic 19.34 vesamenu.c32
-rw-r--r-- 1 root root 4744976 15 dic 19.34 vmlinuz-linux

./changes:
totale 0

What is the problem?
Thank you for attention.
Regards.

![virtualbox_live_15_12_2017_21_10_11](https://user-images.githubusercontent.com/11733578/34059118-ea13fc5c-e1dd-11e7-948f-1d4e56ad81aa.png)

**Comment by Tomas-M** [comment]
During the last two days, I was making some changes to the livekit, and the github master was not stable. Please test again now, download newest linux live kit from github.

If you still get the same error, then you can try to use `lsmod` to see if your cdrom modules are loaded, you may try to mount the iso manually on the command prompt (after the fatal error), or see dmesg for some messages. You may also try to add 'debug' boot parameter to see all executed commands, if that helps.
