### ISSUE TITLE
RPI Support

### ISSUE THREAD

**Issue by godane** [Tomas-M/linux-live#39]
I would like to see raspberry pi support based debian armhf arch.

**Comment by Tomas-M** [comment]
Me too, patches welcome :)

Tomas M

**Comment by godane** [comment]
So i found a way to do slax on raspberry pi. I ended up taking the berryboot.img file and adding your init, config and livekitlib into it. I also used berryboot's kernel cause debian has armmp kernels and there not working where this one does. i only tested from= command in the cmdline.txt file. It boot my version of slax from usb stick so at least that will work with out changes.

**Comment by Tomas-M** [comment]
So you used berryboot kernel and img file? Does it have AUFS support?

**Comment by jsuntheimer72** [comment]
This is awesome!  Very exciting!

**Comment by godane** [comment]
aufs support is in the berrybot kernel image

**Comment by godane** [comment]
so i have coming up with a better way to do this so we still have full berryboot support with slax. Its a bit of mess but the idea is to copy berryboot.img and make squashfs file with your code in it. 
The berryboot.img will have custom if statement and custom copy of transfer_initramfs function. The only change is /??* to /squashfs/??*. I then have a if statement to look for 000-slax-setup.sb for some custom code. Otherwise it do its normal berryboot thing. 

custom berryboot init file: https://pastebin.com/aXp375Q3

code to extracting the berryboot.img file: dd if=berryboot.img bs=64 skip=1 | gzip -dc | cpio -div
code to make that file in folder of extract: 
find . -print | cpio -o -H newc 2>/dev/null | gzip -f > ../initramfs.img
mkimage -A arm -T ramdisk -C none -d initramfs.img berryboot.img

001-slax-setup.sb is just the extract files of berryboot.img with your code copied into it. 

I hope all of this helps.

**Comment by DaniellMesquita** [comment]
@Tomas-M

**Comment by Tomas-M** [comment]
I made a public promise, that if there is 200 patreons on www.patreon.com/slax then I will attempt to make Slax based on ARM architecture for RaspberryPI.

So if you wish this happen, please consider supporting Slax through Patreon :-)
