### ISSUE TITLE
There is no way do represent this file size

### ISSUE THREAD

**Issue by ShixiangWang** [Tomas-M/linux-live#42]
root@wsx:/tmp# ./gen_linux_iso.sh 
I: -input-charset not specified, using utf-8 (detected in locale settings)
genisoimage 1.1.11 (Linux)
Scanning .
Scanning ./linux
File ./linux/01-core.sb is larger than 4GiB-1.
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.

How to specify the file size?

**Comment by Tomas-M** [comment]
It looks like the ISO9660 standard does not allow files bigger than 2GB.
You can add -allow-limited-size parameter to gen_linux_iso.sh (after the genisoimage command) but there are some drawbacks. Read `man genisoimage` and search for allow-limited-size...
