### ISSUE TITLE
Trouble booting

### ISSUE THREAD

**Issue by Shion093** [Tomas-M/linux-live#43]
Hi guys, I just want to clarify the last step, what do you mean by _ run bootinst.sh from the boot subdirectory _  ? Can you show me a few more steps to accomplish this. Thanks and sorry for creating a new issue just for this, I couldn't find any info on google or the closed/open issues on the repo.

**Comment by Tomas-M** [comment]
Last step of what steps?
You simply chdir to the 'boot' directory, and you run the file bootinst.sh which is inside.
The location of boot directory depends on what livekit distro you are using. If you built your own, it will be ./yourname/boot, for example ./linux/boot/ or ./slax/boot/
