### ISSUE TITLE
xlunch failed install

### ISSUE THREAD

**Issue by saymoncoppi** [Tomas-M/linux-live#45]
Hello Tomas!
Im trying to install xlunch but im getting this error:

gcc xlunch.c -o xlunch -lImlib2 -lX11 -O2 -s
xlunch.c:13:22: fatal error: X11/Xlib.h: file not found
 #include <X11/Xlib.h>
                      ^
compilation terminated.
Makefile:40: recipe for target 'xlunch' failed
make: *** [xlunch] Error 1

Im using this script here:
https://github.com/Tomas-M/linux-live/blob/master/Slax/debian/modules/03-desktop/build

Some foruns says to install libx11-dev, but doesnt fix.
Do you have any idea to fix this?

Best regards

**Comment by Tomas-M** [comment]
I do not remember what package to install for this.
But I always do `apt build-dep fluxbox` and this installs all build dependencies of fluxbox and it is sufficient for xlunch.

**Comment by saymoncoppi** [comment]
Hmmm I told the secret... Im trying to use openbox instead of fluxbox.

Curiously as I told you even installing libx11-dev doenst work. Do you have other ideas to try?

**Comment by Tomas-M** [comment]
Does the file exist? /usr/include/X11/Xlib.h
If yes, try to copy it to /usr/include/
I have no other suggestions
