### ISSUE TITLE
Building initramfs image error

### ISSUE THREAD

**Issue by mdbosworth** [Tomas-M/linux-live#47]
Thank you for this set of scripts. I've propley setup the config file to point to proper location of files. But I seem to run into an error during an initial stage, which I believe to be very important. Here is the output in my terminal
`Changing current directory to /home/bosworth/Storage/linux-live`
`Building intramfs image...`
`depmod: ERROR: could not open directory /tmp/arch-initramfs-4181/lib/modules/4.15.14-1-ARCH: No such file or directory`
`depmod: FATAL: could not search modules: No such file or directory`
`Parallel mksquashfs: Using 2 processors`
`Creating 4.0 filesystem on /home/bosworth/Storage/tmp/arch-data-4170/arch/01-core.sb, block size 524288.`
The script begins creating the filesystem, yet without initramfs?
I don't understand what the ERROR means. 
Does the script create a folder arch-initramfs-4181 within /tmp? 
Do I need to create the folder?
`usr/lib/modules/' is the location of my kernel?

here's my config file
`LIVEKITNAME="arch"`
`VMLINUX=/boot/vmlinux-linux`
`KERNEL=$(uname -r)`
`MKMOD="bin etc home lib lib64 opt root sbin srv usr var`
`NETWORK=false`
`LIVEKITDATA=/home/bosworth/Storage/tmp/$LIVEKITNAME-data-$$`
`BEXT=sb`
`LMK="usr/lib/modules/$KERNEL`

mb

**Comment by Tomas-M** [comment]
Hm, what returns uname -r?
Do you really think that your kernel modules are in  usr/lib/modules?  This is usually in /lib/modules

**Comment by mdbosworth** [comment]
uname -r returns 4.15.14-1-ARCH

haha, you answered my question with your question. No error returned when I switched my kernel folder back to /lib/modules. Sorry for bothering you. Its working now. 
mb
