### ISSUE TITLE
image build will not boot

### ISSUE THREAD

**Issue by hdt551** [Tomas-M/linux-live#52]
I am attempting to make a usb bootable copy of a minimal debian install.  
I am installing schroot, squashfs-tools, zip and genisoimage

Everything appears to go fine, I run the build script, it completes, then I make the iso and copy it to the usb drive with
dd if=/tmp/linux-x86.iso of=/dev/fdc

Booting from the usb disk always results in "selected boot device failed"

I have tried this with both a debian 8.10 and 9.4 with the same results.

I tested the dd method of writing an iso file with the debian iso and it booted fine.
I also tried writing the iso file with the windows isotousb program but it fails with a error message.
Can you confirm the  v2.1 version is working ok?
Appreciate any other suggestions as to what I am doing wrong.

**Comment by Tomas-M** [comment]
Do not use dd to copy to usb disk, this will never work for Slax, since the iso is not in isohybrid format.
Instead, copy the iso contents to your USB drive and run bootinst.sh script from boot directory.

**Comment by hdt551** [comment]
As you said, using the bootinst.sh script created a bootable usb drive, thank you.
