### ISSUE TITLE
pxe boot 

### ISSUE THREAD

**Issue by hdt551** [Tomas-M/linux-live#54]
I thought I had this working but I was mistaken.  I now understand it is very hit and miss to boot a linux based iso.

I would like to boot a custom debian build over pxe but it does not have to be an iso. 
I can build the image using linux-live and install it to a usb drive and it works fine.
I would like to boot this same image from a pxe server.  
I see in discussions about pxe booting slax it says you need a PXEFILELIST to reference the .sb file.

I am hoping this same method will work with a linux-live built image.  If so, could you provide an example of what the PXEFILELIST would look like.

**Comment by Tomas-M** [comment]
PXE support has been recently fixed in linux-live.
You can run your live distro on one computer, and start PXE server right away on it by using this simple script:
https://github.com/Tomas-M/linux-live/blob/master/Slax/debian/rootcopy/usr/bin/pxe

**Comment by hdt551** [comment]
Thank you.

**Comment by srikalyan** [comment]
@Tomas-M can you provide a good example on how to do this. I got the ISO but seems like I am unable to get it pxe boot. If there is an example that would be great.
