### ISSUE TITLE
Can you please provide a arch linux supported script?

### ISSUE THREAD

**Issue by Rizwan-Hasan** [Tomas-M/linux-live#55]
Actually I am not so familiar with debian because I use arch linux. I also own a derivative distro MagpieOS. I used your script 2 years ago when slax is based on slackware and script also works fine on any distro. But now it's based on  debian and I am having issue in Arch LInux.

**Comment by Tomas-M** [comment]
I do not know how to install aufs into Arch Linux, so I cannot help here, I'm sorry.

**Comment by Rizwan-Hasan** [comment]
Than would you mind if I try my best to create one from your's one for arch? ☺

**Comment by Tomas-M** [comment]
Sure feel free :) If you find a problem preventing you to make a liveCD from Arch, please debug it and share your findings. Thank you
