### ISSUE TITLE
Can't do savechanges because "no space left on disk"

### ISSUE THREAD

**Issue by duhanwijaya** [Tomas-M/linux-live#57]
Hi Tomas, I'm a big fan of your work. So I've been using Slax for the last two months. I have an issue which is I can't do `savechanges` because no space left on disk. My `/run/initramfs/memory/data/slax` takes up to 14Gb and I still have 10Gb free space on that disk but when I do `savechanges` it pops up error saying there's no space left on disk. It still managed to create the `.sb` file but when I copy the `/slax/` into USB and boot it up, it can't run the new `.sb`file.

How to solve this issue? Thanks a lot!

**Comment by Tomas-M** [comment]
The `savechanges` script works this way:
1) it copies (duplicates) all changed files to /tmp (which is in RAM memory)
2) then it deletes things which are not needed (caches, etc)
3) then it packs everything into a squashfs module.

So as you can see, it needs to duplicate all your changes in RAM memory first in order to save it. It is important to find out which part has insufficient disk space. It is possible that you are running out of RAM memory (for phase 1). Try to delete files which are not important before you run savechanges.

**Comment by duhanwijaya** [comment]
Thanks Tomas. I still have some questions.
1. What happened if the `savechanges` process fails in step one? If I redo the `savechanges` command, what changes will it be saving?
2. Can I delete the `changes2652` directory inside `/tmp` if step one failed?
3. This is a bit out of the context, for example : if I made changes A and save it into A.sb, then I made changes B and save it into B.sb, do I still need to keep A.sb? Or can I delete it?

Thanks again Tomas!

**Comment by Tomas-M** [comment]
You can safely erase the directory in `/tmp`, the `savechanges` script apparently does not know how to cleanup properly in case of failure. On next run, it creates another temporary directory, so it is safe to run it multiple times even if it does not cleanup from the previous run.

If you make changes in a.sb and reboot, then a.sb is a part of the active read-only filesystem and subsequent `savechanges` will only save **newly changed files**, so you will need both. But if you create a.sb and then during the same session you create b.sb, then b.sb contains everything so you can erase a.sb

**Comment by Tomas-M** [comment]
edit

**Comment by ceremcem** [comment]
Interesting. What do you suggest when our `changes` folder doubles the size of our available RAM? Can't we simply save our changes?

**Comment by ceremcem** [comment]
My current workaround here: [`savechanges`](https://github.com/ceremcem/slax-notes/blob/70e843279cdbc45e66f1e15894dbd885693c8879/savechanges).

**Comment by Tomas-M** [comment]
Interesting improvements. Remember that there are important implications when you run your improved savechanges script:
- you need to boot from USB drive, it wont work if you boot from a read-only media such as CD
- the filesystem on your usb drive must support Linux files like symlinks and linux attributes, it cannot be fat32, else you end up with messed up attributes, like all files executable etc.

**Comment by ceremcem** [comment]
Thanks for the review. 

If the media is non-POSIX or readonly, the "use_realfs" mode should immediately fail. 

Even though non-POSIX file systems are out of my scope, maybe I can create a temporary container and format it as ext* and use as usual or maybe directly format it as swap and include it into the swap area.

One more improvement I can think of is somehow creating partial `.sb` archives with smaller amounts of changes data and then, somehow concatenating them. The #94 will make this absolutely possible.
