### ISSUE TITLE
Bad message after successfull build

### ISSUE THREAD

**Issue by Wonno** [Tomas-M/linux-live#60]
After successfull build is says_

> Finished. Find your result in /tmp/linux-data-3383
> To build ISO, run: /tmp/gen_iso.sh
> To build ZIP, run: /tmp/gen_zip.sh

Actually those files are named slightly different. 
_/tmp/gen_linux_iso.sh_ and _/tmp/gen_linux_zip.sh_ would be correct.

**Comment by Tomas-M** [comment]
Thank you, and let me apologize for slow reaction.
Fixed by 52c9f07ff49dfcac82182979d3426c227d2189f3
