### ISSUE TITLE
linux-live.org - possible contact - thanks

### ISSUE THREAD

**Issue by georgesuba** [Tomas-M/linux-live#61]
hi Tom,

How are you? I am contacting you regards this website: 
linux-live.org

- I've created php based website which will automatically translate markdown docs/files to nice bootstraped text wit searchable forms (mostly like wiki pages - no databases used) and normal side bootstraped website - html css and js and some imgs - static website. Like newer version of yours existing. If you interesting into replacing your older website for newer design (all open source) I will provide you with git on my server where you can download and edit it the version you want.

Please let me know. - small thanks. George.

PS your website - I mean contact page is not working (latest chrome and ff - linux debian 64b) - it does not show captcha so no one can send you an a msg.

**Comment by Tomas-M** [comment]
Hello, thank you for bug report regarding website, I've removed the captcha verification since it was unused anyway. 

Thank you for your offer, but actually I do not have any markdown docs/files to translate into a website.

**Comment by georgesuba** [comment]
ahoj Tom,

Nakodil jsem ti novou site.. let me know it you would consider it - I will open git access for you on my server.. nothing complicated - works same as github. - thanks.

## Linux Live Kit Website Repo

hi, this is [original repo](https://git.topfreelancer.co.uk/gs/linux-live-kit-website) for [https://www.linux-live.org/](https://www.linux-live.org/) website created by me - [George Suba](http://topfreelancer.co.uk). This is static html website template which will even work on your localhost - just open html file with your browser. It is based on bootstrap 4, font awesome and other modern technologies. Site is more attractive, easier to navigate and mobile devices friendly, even fast within 2G mobile networks. 

**Note:**

This is static html website template which will even work on your localhost - just open html file with your browser. The template was coded to be hosted online on [https://www.linux-live.org/](https://www.linux-live.org/) domain so if you will click on logo - it will not work.

There is gimp file located in /images/logo-llk.xcf - editable (like "psd" file) for logo in case you need to change it. Also video.mp4 file is located there as backup in case somehow, someone would remove from YouTube (video is 720p) - you never know even the video it self is open-sourced...

## Demo

You can view and test current code here @ [suba.uk/tom](http://suba.uk/tom/)

## Install

Just clone repo and upload contents of the folder to your apache server (in /public_html folder). 

## Modifications

it is plain html5, so gedit or nano or any other text editor would do it for you. You may edit meta tags regards the keywords however you can leave it empty - that way you will stay on search engines exactly on same position. 

## License

This website template is released under GPLv3 License.

**Comment by Tomas-M** [comment]
Hello, this is very nice, I am happy to use it.
Unfortunately the link to your [original repo](https://git.topfreelancer.co.uk/gs/linux-live-kit-website 
) seems broken  - error 404

**Comment by georgesuba** [comment]
Hi Tomas, its not broken, I just forgot to make repo public from private mode. I'm sorry! try again :)

**Comment by Tomas-M** [comment]
Thanks!
It's live now :]

**Comment by georgesuba** [comment]
Hi Tomas, 

that's great! let me know if you would need any help with that or other sites and be sure to ping me at any time about it.. I am happy to help here. and BTW thanks for linux live kit - I really love it! - finally closed ;)
