### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by therapyuser** [Tomas-M/linux-live#66]
when booting my live created iso it stays stuck on looking for linux data in /linux data
then it says "Fatal error occured - could not locate linux data

**Comment by therapyuser** [comment]
i just added aufs ect and it still doesnt boot into my iso :(

**Comment by Tomas-M** [comment]
Your kernel needs to have support for the storage device you are booting from.
For example, if you boot from CD, your kernel must have support for CDROM drives and isofs filesystem.

After you get the fatal error, you are provided with a shell prompt, you can use it to mount your boot device manually and investigate the issue.

**Comment by therapyuser** [comment]
I'm using VMware to boot the iso

**Comment by therapyuser** [comment]
Your scripts are my last option to iso my distro which is like 40 GB which
I used system back to make a .sblive copy which gets compressed to 10gb way
above iso 4gb standard :(
