### ISSUE TITLE
Won't boot

### ISSUE THREAD

**Issue by mjhorvath** [Tomas-M/linux-live#67]
I was able to build the ISO file according to directions on your homepage.

However, when I try to boot the ISO in VMWare, I get 

![Clipboard-1](https://user-images.githubusercontent.com/17457030/56461741-b6315f80-6385-11e9-98a2-5a1c2a54d276.png)

Host: Windows 7 x64
Guest: Mint 19.1 x64

I downloaded the latest linux-live-master ZIP from github today. Not sure what else to do. Thanks.

**Comment by mjhorvath** [comment]
I also tried executing "isolinux.bin.update", but it asks for a directory for isolinux search paths, and I don't know what to enter. (The readme doesn't mention this step.)

**Comment by Tomas-M** [comment]
You are provided with a shell prompt. Use it to investigate. Try to mount the boot drive, try to find /linux/ directory on it.
