### ISSUE TITLE
Drive Size Limitations

### ISSUE THREAD

**Issue by computermaster0101** [Tomas-M/linux-live#69]
There seams to be some drive size limitations. I've executed the processes to write my linux live to a few different USB drives. One is 64gb and presents no issues and the other is 256gb and continuously results in "cannot find linux live data" and a message that says "this should never happen". Please let me know what additional information I can supply or if there are limitations on the size of drive. 

As another troubleshooting setup both USBs with E2B and dropped the ISO into the _ISO/Linux directory. I was presented with the same results. On both drives, E2B would boot and I could select the linux iso; on the 64gb drive, boot succeeds but on the 256gb drive boot of the iso fails with the same message "cannot find linux live data"

[Update] Completed the same steps on a 128gb usb drive and it worked

**Comment by Tomas-M** [comment]
I am not sure if I understand your setup properly.
Do you have the ISO file on your USB drive?
The only supported way is to copy the iso **contents** to the usb device, and run /linux/boot/bootinst.sh to make it bootable.

I do not know what is E2B but most likely I cannot support it in any way.

There is no limit for drive size, so it must be something else.

**Comment by computermaster0101** [comment]
Thank you for the fast response! To share in case your interested, here is the E2B info. http://www.easy2boot.com/. It couples well with building linux-live isos to provide mutliboot usb drives. I've been using it for years to boot live iso's since it can boot windows on a vhd, kali live iso, ubuntu linux-live iso, etc. 


In any case, here are the steps im taking as an example

1. extract linux-x86_64.zip to the root of my fat32 formatted usb
2.  cd to (USB)/linux/boot/
3. execute bootinst.bat/bootinst.sh as administrator/root (i've done this on Windows and Linux to ensure im not missing something obvious)
4. Remove drive from 'imaging' machine and connect it to 'test device'
5. boot to USB


When I use a 64gb usb drive and a 128gb usb drive I experience no issues but when I use a 256gb usb drive I run into the errors previously stated. I'll be looking at testing with a 500gb and 1tb drive today to see if I run into anything different. 

Also if it helps, below is my script used against a newly installed Ubuntu18.04 server to generate my iso and zip files im using to boot. To execute the script correctly i:

1. install ubuntu 18.04 server
2. at the end of the install, before the reboot, alt+f2 to drop into shell and execute the script with syntax scriptname.sh username password
3. reboot the machine and login

The script will create a new .profile file for username so commands are executed on first login. The steps taken on first login are:

1. Disable command history
2. Add selected base packages (xterm, xorg, google-chrome, openbox, python, virtualbox)
3. Create a new .profile for the user
4. Disable command history and start xorg on future logins
5. disable screen time out for xorg
6.enable forced automatic login
7. generate the iso/zip using linux-live
8. copies the generated files from /tmp to ~/
9 restarts the machine

when the restart completes I am able to grab the generated files and use E2B to boot the iso directly or write the files in the .zip directly to a formatted usb. 

If any more information is needed regarding what im doing and how to recreate the issue please let me know. Writing the files is the generated .zip to the 256gb usb and booting to the usb is my desired goal. E2B and the other information is provided to help share my processes for clarity.

[embed-setup.sh.txt](https://github.com/Tomas-M/linux-live/files/3198766/embed-setup.sh.txt)

**Comment by Tomas-M** [comment]
I see no reason why it cannot find the live data on 256GB flash drive. Does it use GPT or MBR for partitions? 

When the live os fails to start and prints error message that it should never happen, you are provided with a command prompt. Try to mount the usb device manually, try to cat /proc/partitions to see the drive is recognized, try blkid, try dmesg. You should be able to collect some debug data. Hope it helps.

**Comment by computermaster0101** [comment]
I haven't had the chance to test with additional drives due to other demands. I intend to test next week and will keep this ticket updated.

**Comment by computermaster0101** [comment]
Sorry for the delayed update. Looks like this was either related to the drive being formatted by the ubuntu installer formatting the drive as gpt. When deleting the partitions and extracting the .zip back to the drive the os was initially installed on, the partition table must be recreated to mbr type. Through out testing I also changed the enclosure of my drive but im confident the issue was related to mbr vs gpt. Thank you for all your help!
