### ISSUE TITLE
slax always downloads to "slax/modules" folder even when from= is specified

### ISSUE THREAD

**Issue by azuer88** [Tomas-M/linux-live#7]
slax downloads modules into "slax/modules" even when from= specifies another folder.  to resolve this, i added this line:

```
         if [ ! "$1/$FROM" == "$1/$LIVEKITNAME" ]; then
            mount --bind $1/$FROM $1/$LIVEKITNAME        
         fi                               
```

right after (in function find_data_try):

```
      # search for bundles in the mounted directory                                   
      if [ "$(find "$1/$FROM" -maxdepth 1 -name "*.$BEXT" 2>/dev/null)" != "" ]; then 
         # we found at least one bundle/module here                                  
         mount -o remount,rw "$DEVICE" "$1" 2>/dev/null            
```

so now, any slax module that is downloaded will reside in the "modules" in the folder specified by from=.

*\* this will hide any existing "slax" folder in that location.

another solution may be to save the mount point of the from= folder and have the slax script read that in get_bundle_storage_dir().

**Comment by Tomas-M** [comment]
closing old issues, if your problem persists with newest code, feel free to reopen
