### ISSUE TITLE
Add support for dancesplash

### ISSUE THREAD

**Issue by danielkot** [Tomas-M/linux-live#73]
Here I leave my improvements for splash screen in initramfs sequence...
You can apply my patch using `git apply dancesplash.txt`, then pun 2 tar.gz files in `./initramfs/static`.
You can change the logo inside dancesplash tar file by patch in archive `/etc/dancesplash.conf` or simply overwrite `cow_logo.jpg` in `/lib` dir in archive
![image](https://user-images.githubusercontent.com/24195416/59981811-6121fc00-9609-11e9-9d32-a6adab49e02a.png)

[dancesplash.tar.gz](https://github.com/Tomas-M/linux-live/files/3318564/dancesplash.tar.gz)
[glibc-2.7.tar.gz](https://github.com/Tomas-M/linux-live/files/3318565/glibc-2.7.tar.gz)
[dancesplash.txt](https://github.com/Tomas-M/linux-live/files/3318566/dancesplash.txt)

**Comment by Tomas-M** [comment]
If you statically compile dancesplash binary with uclibc, you'll get rid of the need to include big glibc

**Comment by Tomas-M** [comment]
What is the project page of dancesplash? Where are the sources? Thank you

**Comment by danielkot** [comment]
this project does not have a www page, but i'll give you source in attachment.
NOTICE: Compile using gcc with 4.x.y version, otherwise errors are occurred,

[dancesplash-0.2.zip](https://github.com/Tomas-M/linux-live/files/3319984/dancesplash-0.2.zip)

**Comment by Tomas-M** [comment]
Hm, so where did you download it if it has no www page? :)

**Comment by danielkot** [comment]
from [there](https://sourceforge.net/p/pdaxrom/code/HEAD/tree/trunk/dancesplash/)

**Comment by danielkot** [comment]
because the pdaxrom website is dead, I thought that I would write that it does not have this page anymore.

**Comment by Tomas-M** [comment]
I tried to compile the sources and it didn't work so I gave up

**Comment by danielkot** [comment]
Hmm interesting, are you compiling using which toolchain? shared or static?
Better reproduce steps that what are you doing.

**Comment by Tomas-M** [comment]
I installed make, freetype libs, and jpeg/png libs, then replaced i386-linux-.... prefixes everywhere in Makefile, so it uses gcc instead of i386-linux-gcc and so on ... there were some compile errors complaining about wrong variable type... I gave up. The software is 9 years old with no maintainer...
