### ISSUE TITLE
If I create it on a raspberry pi, will the live distro boot on this device?

### ISSUE THREAD

**Issue by DaniellMesquita** [Tomas-M/linux-live#76]

**Comment by Tomas-M** [comment]
Most likely not. Raspberry pi has different way how it boots

**Comment by computermaster0101** [comment]
Hello! You might check out https://github.com/Tomas-M/linux-live/issues/39. It looks like this topic was previously visited. Have a great day!

**Comment by rrottmann** [comment]
Here is a work-in-progress version of a bootable slax-like raspberry pi setup: https://github.com/rrottmann/rpi-slax
It took some time to figure out the correct way how to setup the bootloader correctly to boot with initramfs.
But the good news are that basically the setup is feasable and works even with limited resources on a Raspberry Pi 2.
There is still a bug in the Frankenstein initramfs, which is cobbled together from buildroot, RaspiOS and linux-live.
With some manual intervention, one can boot into a debian buster root and can use the slax customization scripts as usual.
