### ISSUE TITLE
Deploying zip to root partition of aws ec2 instance

### ISSUE THREAD

**Issue by computermaster0101** [Tomas-M/linux-live#77]
Im attempting to run the live os on an EC2 instance in AWS. 

I was able to:
1. create an EC2 instance with Ubuntu
2. run the linux-live scripts to generate the .zip
3. attach a second volume 
4. format it as mbr with a single ext4 partition, 
5. mount said partition to /tmp/test
6. mv the .zip to /tmp/test and extract it
7. run /tmp/test/linux/boot/bootinst.sh
8. stop the ec2 instance
9. remove both ebs volumes
10. attach the second volume to the ec2 as the root volume
11. restart the instance

The EC2 instance stalls at the syslinux screen for selecting "Run Linux" or "Run Linux Debug" 

Have you tried to, or has anyone tried to run this in a similar way? Thank you in advance for your help. If you need more details please let me know. 

Note: to reduce the cost of testing this type of a setup, im using the t2.micro from aws which falls within the free tier.

**Comment by Tomas-M** [comment]
So the boot loader has been successfully located and executed, but then it freezes? Is there a counter on that screen? Is it running? (it should count 30 seconds or so). Can you use arrow keys and Enter to select one of the options "Run Linux" or "Run Linux Debug" ?

**Comment by computermaster0101** [comment]
![image](https://user-images.githubusercontent.com/10255679/61966222-5f907e80-af8f-11e9-93a2-4e1e3f6e1703.png)


Here is a screenshot of the virtual instance pulled using AWS's web console. The instance never moves past this point. Also since it is a virtual instance in the AWS cloud actions available before the OS is booted are limited. 

I'd be happy to collaborate on this together to see if it is possible to run an instance in the cloud using linux-live.

**Comment by Tomas-M** [comment]
I don't know how AWS works.
If the boot hangs after the timer elapses, it can mean syslinux is unable to load vmlinuz and initrfs.img to boot.
But I am not sure if that is a problem of syslinux, or a problem of AWS

**Comment by computermaster0101** [comment]
Your AWESOME! Turns out, /vmlinuz was not included in the linux-live zip. I'll do some more research to see if i can identify why this happened but I was able to copy the /vmlinuz from one volume to my linux-live volume then reattach the linux-live volume as the root volume on the ec2. Thank you for your help!

**Comment by Tomas-M** [comment]
The path for vmlinuz is configured in "config" file in linux-live directory.
I can see there is no test for existence, so if it is not configured properly, nobody notices.
Maybe I should add a test there, and if vmlinuz (as defined in config file) is not found, fail and inform the user, so he can fix the issue.

**Comment by Tomas-M** [comment]
Should be better now by 05af29f8d14b3311517caead70ed8391ac7289bd

**Comment by computermaster0101** [comment]
I stand by my assessment - you're awesome! Thank you!

**Comment by Tomas-M** [comment]
Beware, the mentioned patch had a side effect I didn't notice before, it touched another line (generation of readme.txt file). That part was not intended, and was fixed again by 72de891a3dd94501beefebc1e803ecd471827104
