### ISSUE TITLE
Got an error when I boot ISO

### ISSUE THREAD

**Issue by dazuimao1990** [Tomas-M/linux-live#79]
![image](https://user-images.githubusercontent.com/33855684/62034942-74844080-b221-11e9-8a61-5ae9c7d29260.png)

I have install the ISO in Parallels Desktop ,but it went wrong.
I made iso from ubuntu1604.
what can i do ? tks

**Comment by Tomas-M** [comment]
You need aufs support enabled for yout kernel, either compiled in directly, or as a kernel module.
