### ISSUE TITLE
Partition tables matter for bootable USB drives

### ISSUE THREAD

**Issue by neilwalkinshaw** [Tomas-M/linux-live#80]
Hi Tomas,

This is an excellent project - thanks a lot for developing and maintaining it.

One item that could perhaps be added to the instructions (which has taken me several weeks to figure out) is that for a bootable USB, the drive has to be formatted with a Master Boot Record partition table (not GUID), otherwise the boot installation script will not make a bootable USB drive.

Many thanks.

**Comment by oifii** [comment]
Hi Tomas, great project indeed. I too needed many attempts before succeeding. I was using mkusb along with the iso build using your linux-live build script. It would be great if someone figured out the way to have the ./bootinst.sh script or an equivalent script to fix boot when not using master boot record partition table. Cheers, Steph.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
