### ISSUE TITLE
extlinux.x64 Permission Denied 

### ISSUE THREAD

**Issue by technotherion** [Tomas-M/linux-live#81]
Using Xubuntu 18.04 in VirtualBox - 

I modified the bootinst.sh script to add "set -eux" to the top for additional debug info

```
sudo sh ./bootinst.sh 
+ pwd
+ CWD=/media/mold/4098-3F92/moldkit/boot
+ dirname ./bootinst.sh
+ BOOT=.
+ cd .
+ cut -d   -f 1
+ tr -s  
+ tail -n 1
+ df .
+ PART=/dev/sdb1
+ sed -r s:([0-9])[a-z]+$:\1:i
+ sed -r s:[0-9]+$::
+ echo /dev/sdb1
+ DEV=/dev/sdb
+ uname -m
+ ARCH=x86_64
+ [ x86_64 = x86_64 ]
+ ARCH=64
+ EXTLINUX=extlinux.x64
+ ./extlinux.x64 --install .
./bootinst.sh: 19: ./bootinst.sh: ./extlinux.x64: Permission denied

```
when running "./extlinux.x64" on its own I get "Permission denied"
when running with sudo I get "command not found" (??)

The script is unable to run

**Comment by Tomas-M** [comment]
Interesting. Is your system 64bit or 32bit?

**Comment by Tomas-M** [comment]
What file mode bits are set for the file extlinux.x64? (chmod)

**Comment by palucki** [comment]
Hi @technotherion, 
are you sure your drive is mounted with _exec_ option enabled?
I've had similiar problems when using Ubuntu, by default USB was mounted with options that implicitly implied _noexec_ option.
Please try to unmount with _sudo unmount path_to_mount_ and then just _sudo mount path_to_media_ and share the results ;)

**Comment by felixlohmeier** [comment]
I also stumpled upon it. Example of @palucki's solution for linux-live-kit called `linux` and usb-drive at `/dev/sda1` formatted as FAT:
```
[felix@tux ~]$ sudo umount /dev/sda1
[felix@tux ~]$ mkdir usb
[felix@tux ~]$ sudo mount /dev/sda1 usb
[felix@tux ~]$ cd usb/linux/boot
[felix@tux boot]$ sudo ./bootinst.sh
. is device /dev/sda1
Boot installation finished.
```

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
