### ISSUE TITLE
Mouse moves only up or down

### ISSUE THREAD

**Issue by alexjkitty** [Tomas-M/linux-live#83]
I made live usb ubuntu 18.04.03 LTS amd64 with linux-live.
After boot live usb mouse moves only up or down. When i press right mouse button it moves to the right - to the end of screen. 

What to do? I tried to include more drivers in usb while creating initramfs... no help.

**Comment by alexjkitty** [comment]
i will try Debian

**Comment by alexjkitty** [comment]
SOLVED by include into initramfs in the right place
this line:

copy_including_deps /$LMK/kernel/drivers/usb/host/whci

**Comment by Tomas-M** [comment]
Thank you

**Comment by Tomas-M** [comment]
Hm, I think you probably solved it by including some other module.
There is already
copy_including_deps /$LMK/kernel/drivers/usb/host
which includes the whci directory as well. So there is a chance something else is needed.

**Comment by alexjkitty** [comment]
here what i've done, yes it's something more

copy_including_deps /$LMK/kernel/drivers/usb/storage/usb-storage.*
copy_including_deps /$LMK/kernel/drivers/usb/host
copy_including_deps /$LMK/kernel/drivers/usb/host/whci
copy_including_deps /$LMK/kernel/drivers/usb/common
copy_including_deps /$LMK/kernel/drivers/usb/core
#copy_including_deps /$LMK/kernel/drivers/hid/usbhid
copy_including_deps /$LMK/kernel/drivers/hid/hid
#copy_including_deps /$LMK/kernel/drivers/hid/uhid.*
#copy_including_deps /$LMK/kernel/drivers/hid/hid-generic.*

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
