### ISSUE TITLE
Syntax error: ")" unexpected  in extlinux.x32

### ISSUE THREAD

**Issue by jpricaud** [Tomas-M/linux-live#85]
Hi,

when executing bootinst.sh, I get the error:

```
./extlinux.x32: 1: ./extlinux.x32: Syntax error: ")" unexpected
Error installing boot loader.
Read the errors above and press enter to exit...
```

I am using **linux-live-2.3.tar.gz** uploaded from https://www.linux-live.org/
I am trying to make a live usb from an ARM ubuntu 16.04.6 LTS

Any idea of what is wrong?

Thank you
Best Regards

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
