### ISSUE TITLE
UDF + Fatal error occured

### ISSUE THREAD

**Issue by IvarSvart** [Tomas-M/linux-live#87]
Hi!
I was able to build the ISO file (file size was more than 4 gb from Debian GNU/Linux 10 buster) according to directions on your homepage with:
`cd /tmp/linux-data-574 && /usr/bin/genisoimage -allow-limited-size -o /tmp/linux-i686.iso -v -J -R -D -A linux -V linux -no-emul-boot -boot-info-table -boot-load-size 4 -b linux/boot/isolinux.bin -c linux/boot/isolinux.boot .`

However, when I try to boot the ISO in VM VirtualBox, I get:
`Fatal error occured - Could not locate linux data`

![VirtualBox_debian_live_22_10_2019_08_47_07](https://user-images.githubusercontent.com/56856560/67258143-a7e50d00-f4a8-11e9-830c-555c7765fb14.png)

What should I do to make live-kit boot properly? Thanks.

**Comment by Tomas-M** [comment]
Most likely there us no udf support in initramfs
