### ISSUE TITLE
VMware Workstation - Fatal error occured - Could not locate linux data

### ISSUE THREAD

**Issue by Simone-V** [Tomas-M/linux-live#88]
Hello Tomas,
I created file zip from VM Kubuntu 16.04 32 bit, deployed on VMware Workstation 12. When I install file zip on VM Windows 7 Enterprise 32 bit and reboot the virtual machine, I received this fatal error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/56981464/67527923-675bde00-f6b8-11e9-9ed5-3b8629bd70eb.png)

On the OS linux there are the following upgrated packages: squashfs-tools, genisoimage and aufs-tools.

I didn't change config file on linux-live-master folder.

You could help me?
Thanks.

**Comment by shaynethiessen** [comment]
Had the same problem. Don't use the scsi drive type in vwmare (try sata) and it will work fine.

**Comment by DemaxDragonTix12** [comment]
same problem with vmware workstation 16... I also tried changing from SCSI to SATA.. did not work

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
