### ISSUE TITLE
Won't show in GRUB

### ISSUE THREAD

**Issue by minecraftchest1** [Tomas-M/linux-live#89]
I followed all of the installation steps with my destination being another hard drive. With both hard drives connected, it boots to my primary os. If I disconnect my primary hard drive, it boots to the Live os just fine. Any advice?

**Comment by shaynethiessen** [comment]
You could change the boot order in bios so if a USB is connected it tries to boot from that before trying your hard drive.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
