### ISSUE TITLE
run isolinux.update error makefile 

### ISSUE THREAD

**Issue by yashutorie** [Tomas-M/linux-live#90]
hello, 

i tried to make iso form linux live, i've read the readme to run isolinux.update, at the end of process i found error : 

https://pastebin.com/bPN6TsJz

is that ok?

**Comment by Tomas-M** [comment]
Just few days ago I updated the script to ignore errors. Are you using latest version from github?

**Comment by yashutorie** [comment]
> Just few days ago I updated the script to ignore errors. Are you using latest version from github?

sorry I haven't try it, i'll try the latest from github, and update the result.

**Comment by yashutorie** [comment]
> Just few days ago I updated the script to ignore errors. Are you using latest version from github?

I've tried the latest, no error thanks.
