### ISSUE TITLE
Unable to make bootable CD/DVD with Ubuntu 18.04

### ISSUE THREAD

**Issue by brad-colbert** [Tomas-M/linux-live#91]
I'm unable to successfully run tools/isolinux.bin.update with it ending in error due to multiple definitions of memcpy and memset in the source for syslinux.

Is there some special steps I need to make this work?

**Comment by Tomas-M** [comment]
Did you try to download latest version of this repo? I made some changes like a week ago or so

**Comment by brad-colbert** [comment]
I was using the v2.3 tag.  I'll try the head on git and let you know how it works out.

**Comment by brad-colbert** [comment]
What directory do I add for:

> --------------------------------------
> Add directory to isolinux search paths
> 

?

**Comment by brad-colbert** [comment]
I used **/boot** as an answer to the "Add directory to isolinux search paths" and it appears to build.  I manually copied the built files to the bootfiles directory.  I rebuilt my ISO.  I get an error on boot, however.  Same error I've been getting:

> Failed to load ldlinux.c32

What could I be doing wrong?

**Comment by Tomas-M** [comment]
Default directories where isolinux searches for syslinux.cfg (and other files like ldlinux.c32 etc) are like:
/boot/
/syslinux/
/boot/syslinux/
/

The directory you are going to specify here is an extra directory where you can put syslinux.cfg.
For example, for Slax, you add /slax/boot/and that means isolinux boot loader will try to search for syslinux.cfg in the specified directory /slax/boot

So if you are using linux-live scripts, it puts syslinux.cfg in /linux/boot directory for you, so you should specify /linux/boot here.

**Comment by brad-colbert** [comment]
Could the "Failed to load ldlinux.c32" be due to my system booting EFI?

**Comment by brad-colbert** [comment]
I rebuilt it with a system that boots using legacy bios mode but I still get the same error.

**Comment by SafyreLyons** [comment]
I have the same issue with the latest ones on 19.10

**Comment by Tomas-M** [comment]
I think I should review and re-test this

**Comment by AndNovAtor** [comment]
I have the same issue with Lubuntu 18.04 (18.04.3) on booting from ISO - "Failed to load ldlinux.c32".

Workaround that works for me:

1. Move and rename `/tmp/<LIVEKITNAME>-<number>/<LIVEKITNAME>/boot` into `/tmp/<LIVEKITNAME>-<number>/syslinux` (after all files created and all buildings was completed, gen_<LIVEKITNAME>_iso.sh was created - e.g. before creating ISO file)
2. Create ISO with booting into syslinux dir - `change in gen_<LIVEKITNAME>_iso.sh` mkisofs comand into something like this:
`mkisofs -r -V "Ubuntu" -cache-inodes -J -l -b **syslinux**/isolinux.bin -c **syslinux**/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../Ubuntu-x86_64.iso .`
so `gen_<LIVEKITNAME>_iso.sh` will be looks something like this:
`cd /tmp/Ubuntu-data-26421 && /usr/bin/mkisofs -o /tmp/Ubuntu-x86_64.iso -v -J -R -D -A Ubuntu -V Ubuntu -no-emul-boot -boot-info-table -boot-load-size 4 -b syslinux/isolinux.bin -c syslinux/isolinux.boot .`

Seems like ldlinux.c32 should be in syslinux dir from CD root

Btw, @Tomas-M,  why we should to compile syslinux from source? I used syslinux binaries from kernel.org, and my ISO was booting successfully

**Comment by AndNovAtor** [comment]
> I have the same issue with Lubuntu 18.04 (18.04.3) on booting from ISO - "Failed to load ldlinux.c32".
> 
> Workaround that works for me:
> 
....
Ogh wait, I forgot about use this, when building "live system" files:

> Default directories where isolinux searches for syslinux.cfg (and other files like ldlinux.c32 etc) are like:
> /boot/
> /syslinux/
> /boot/syslinux/

So, @Tomas-M, Do I maybe need add `<LIVEKITNAME>/boot` when building syslinux from source 'cos `<LIVEKITNAME>` is in CD root and boot/ldlinux.c32 is in `<LIVEKITNAME>` dir ?

**Comment by theogfx** [comment]
If you change the `LIVEKITNAME` var in `config`, then you should also rebuild the isolinux files (for USB or CD).

Thus when launching `./tools/isolinux.bin.update`, you should specify the following-path:

`/<LIVEKITNAME>/boot`

Don't forget to copy the newly built files to `./bootfiles/` and voilà!

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
