### ISSUE TITLE
How to move changes directory to changes.sb on the fly?

### ISSUE THREAD

**Issue by ceremcem** [Tomas-M/linux-live#93]
We can create `changes.sb` with `savechanges` command. However, this command only creates a new Slax module. How can we atomically:

1. Create an empty `changes.new` directory on the union and redirect all write operations to this folder
2. Remount our changes readonly 
3. Save changes to `changes.sb` module (obviously with `savechanges` command)
4. Mount our `changes.sb` on the fly (this is [explained in the documentation](https://www.slax.org/customize.php))
5. `rm -r /run/initramfs/memory/data/slax/changes/`
6. `mv /run/initramfs/memory/data/slax/changes.new /run/initramfs/memory/data/slax/changes/

How can we handle `#1`, `#2` and `#6`?

**Comment by Tomas-M** [comment]
Part 2 is virtually impossible.
While it is technically possible to remount the changes directory read only if there are no files open, in practice there are always some files open when the operating system is running. So it won't work.
