### ISSUE TITLE
Support multiple changes directories

### ISSUE THREAD

**Issue by ceremcem** [Tomas-M/linux-live#94]
Slax should support multiple changes directories, possibly with `changes-[a-zA-Z0-9-_]` format, where the `/run/initramfs/memory/data/slax/changes/` folder would always be mounted on the top (`rw`). 

# Rationale 

When we need to move our changes to a "`changes.sb`" module, we should be able to completely sure about atomicity (ie. there is no write operations in the meanwhile). If there is a multiple changes folder, we can simply take snapshots, as if it were a BTRFS filesystem: 

1. Move `.../changes` to `.../changes-20200201T1140`. Expecting Slax would continue using this same folder as writable medium. 
2. If a sudden reboot occurs (power failure, etc.) after the rename and before creating the "changes" folder, on the next reboot, an empty "changes" directory will be created while that `changes-20200201T1140` folder is mounted to the `union` before `changes/` as readonly. 
3. If there is no interruption (mentioned in step-2), we should be able to mount `changes/` directory on top of `union`, redirect all write operations to there and remount the `changes-20200201T1140` folder as readonly. Maybe there should be a `set-changes-directory` tool for that purpose. 
4. If we are happy with the changes and merge the changes, we will just move all files from `changes-5` to `changes-4` by overwriting them and delete the `changes-5` folder. This operation would be atomic because if the operation is interrupted in the middle, there is a `changes-4` folder with mixed content both containing `changes-4` version of files and `changes-5` version of files. However, this will not hurt because they would be overwritten in the `union` anyway. 

So, if multiple `changes` directories are supported, a "snapshot" feature would be automatically added to the Slax.

**Comment by Tomas-M** [comment]
I am afraid it is not possible to`redirect all write operations` to a new branch in aufs. Currently open files will always stay open on the branch from which they were opened.

It could work to have a separate changes directory between reboots.
But it will not work properly on the fly during the system is running.

**Comment by ceremcem** [comment]
Okay, regarding to the previous explanation, it's okay not to have a write operation redirection capability at the moment. However, it would be still way useful if we had such multiple changes directory. For example, we can move current changes to a readonly "snapshot" and reboot before a upgrade operation.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
