### ISSUE TITLE
Problem with booting on centos7

### ISSUE THREAD

**Issue by aprotzne** [Tomas-M/linux-live#95]
Hi, 
I would like to create live iso from Centos7.
I have the same problem as giulio1979 (https://github.com/Tomas-M/linux-live/issues/24#issue-249367891) with booting live iso, menu appears with 2 options but is not moving forward. 
I have a 5.4.12-1.el7.elrepo.x86_64 kernel that supports aufs and squashfs. 
- I have done changes in the config file where I changed the path to the kernel file  
- I also tried edit syslinux.cfg
ISO was successfully created with all necessary files included. But when inserted CD into my virtual machine, it loaded menu with 2 options where it got stuck and not moved forward.
Could somebody give me advice about that?  
Thank you

**Comment by Tomas-M** [comment]
Could you rebuild your iso, remove all *.sb files as well as vmlinuz and initrfs.img, and send it to me, I'll have a look.

**Comment by aprotzne** [comment]
I tried to rebuild it from the beginning, but it looks like that now it isn't loading at all.  It is showing an error message "Failed to load ldlinux.c32".
I will drop .zip file in my repo [https://github.com/aprotzne/ho.git](url).
Thank you.

**Comment by raphipod** [comment]
#101 for reference.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
