### ISSUE TITLE
Linux live via USB not works properly

### ISSUE THREAD

**Issue by maframan** [Tomas-M/linux-live#96]
Hi, when in My disk is installed a linux live with your kit, USB with Linux live not boot and boot only that in My disk. If I remove partition on My disk with Linux live the usb boots very well.
What’s the problem?

Thanks a lot

**Comment by voneAbides** [comment]
Did you set boot priority to USB in BIOS?

**Comment by maframan** [comment]
Hi Tomas,

yes, i've configured bios properly.

Regards
Francesco

Il giorno ven 31 gen 2020 alle ore 14:03 voneAbides <
notifications@github.com> ha scritto:

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
