### ISSUE TITLE
Warning: fstab entry for /dev/shm; should probably be for /run/shm unless working around a bug in the Oracle database

### ISSUE THREAD

**Issue by lucbertz** [Tomas-M/linux-live#99]
I get an error on mounting /dev/shm when I use the script on Devuan, using sysvinit:
_"Warning: fstab entry for /dev/shm; should probably be for /run/shm unless working around a bug in the Oracle database"_

If I remove the following line from livekitlib file, the error no longer appears:
`echo tmpfs /dev/shm tmpfs defaults 0 0 >> $FSTAB`

Obviously I'm not sure this is a good solution.

I found this about a similar issue:
https://lists.debian.org/debian-release/2013/01/msg01081.html

In particular:

> If an fstab entry for /dev/shm exists instead
> +of /run/shm, then /dev/shm will continue to be used; note that this is
> +only needed for users of newer versions of the Oracle database, which
> +contain a buggy check for /dev/shm.

**Comment by Tomas-M** [comment]
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.
